-- ============================================================================
-- 2026-09-13 — agent_issues: open-title dedupe enforced at the DB layer
-- Target: qnfo-audit D1
-- Table:  agent_issues
-- Author: qnfo-ops (ops endpoint), autonomous
--
-- STATUS: **APPLIED** 2026-09-13T14:41Z by qnfo-ops via the guarded D1 write
--         path. Verified live — see VERIFIED APPLIED below.
--
-- WHY — issue 784 (AUDIT-FILER-IS-OPS), measured 2026-09-13T14:41:23Z:
--   131 rows created in 24h; 110 in the trailing 30 minutes; the hour bucket
--   2026-09-13T14 alone holds 108 rows. Source split of the 30-minute burst:
--     qnfo-ops                              83
--     ops-exec                              13
--     qnfo-ai-calibration                    7
--     qnfo-ops-fleet-audit-2026-09-13        5
--     ops-fleet-audit                        3
--     qnfo-fleet-advisor                     1
--   ops_ai_log confirms the driver: 8 concurrent `ops-exec` jobs dispatched
--   between 14:37:44Z and 14:40:44Z (180 s), every one carrying the identical
--   prompt "TOO MANY WORKERS DOING TOO LITTLE WORK! PRUNE AND CONSOLIDATE!".
--   Each job is a full tool-enabled agent with D1 write access. Issue 779.
--
--   The table carried NO uniqueness constraint on title — only
--   idx_issues_status and idx_issues_created — so nothing at the storage layer
--   could refuse a re-filed finding. 36 titles are duplicated across the table;
--   all of them sit in closed/wontfix/resolved rows, so the constraint could be
--   installed without a cleanup pass.
--
-- WHAT SHIPPED — a partial unique index. It constrains only rows whose status
-- is 'open', so a defect may still be re-filed after its earlier ticket is
-- closed (status <> 'open' is unconstrained).
--
--   CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_issues_open_title
--     ON agent_issues(title) WHERE status = 'open';
--
-- VERIFIED APPLIED 2026-09-13T14:41Z:
--   sqlite_master now lists 3 indexes on agent_issues:
--     idx_issues_status, idx_issues_created, idx_agent_issues_open_title
--   Precondition checked immediately before applying — 0 rows returned:
--     SELECT COUNT(*) FROM agent_issues WHERE status='open' AND title IN
--       (SELECT title FROM agent_issues WHERE status='open'
--        GROUP BY title HAVING COUNT(*)>1);
--   Enforcement probe (expected to fail, and did):
--     INSERT ... SELECT title FROM agent_issues WHERE id=784   -- duplicate open title
--     -> D1_ERROR: UNIQUE constraint failed: agent_issues.title: SQLITE_CONSTRAINT
--        (extended: SQLITE_CONSTRAINT_UNIQUE)
--   Control probe (expected to succeed, and did):
--     INSERT ... VALUES ('DEDUPE-CONTROL-PROBE-2026-09-13T1441Z', ...)
--     -> accepted; row removed immediately afterwards.
--
-- FAILURE MODE — READ THIS BEFORE CALLING IT FIXED.
--   This index turns a duplicate OPEN filing into an ERROR, not a silent no-op.
--   The filer's INSERT site sits past the 32,768-char read cap on
--   qnfo-ops/worker.js (192,635 B as of 2026-09-13) and CANNOT be inspected
--   from the ops endpoint. If the filer does not catch the constraint error, an
--   audit run that tries to re-file an open issue will now abort instead of
--   silently growing the ledger. That is a deliberate trade — fail closed on a
--   known defect rather than accumulate unbounded duplicates — but it is a
--   behaviour change for EVERY writer to agent_issues (qnfo-ops, ops-exec,
--   qnfo-ai-calibration, qnfo-fleet-advisor, qnfo-pipeline-ops,
--   qnfo-error-selfheal) and it has NOT been tested against their error paths.
--   The control probe above proves the constraint does not block legitimate
--   new titles; it does not prove the writers handle rejection gracefully.
--
-- PREFERRED (NOT YET APPLIED) — silent skip instead of error. SQLite triggers
--   can express ON CONFLICT DO NOTHING semantics via RAISE(IGNORE), but the ops
--   endpoint's write guard rejects the statement ("single write statement
--   only") because a trigger body contains an internal semicolon. Apply this
--   from a D1 console, `wrangler d1 execute`, or a migration runner:
--
--   CREATE TRIGGER IF NOT EXISTS trg_agent_issues_open_title_dedupe
--   BEFORE INSERT ON agent_issues
--   WHEN NEW.status = 'open' AND EXISTS (
--     SELECT 1 FROM agent_issues WHERE title = NEW.title AND status = 'open')
--   BEGIN SELECT RAISE(IGNORE); END;
--
-- ROLLBACK
--   DROP INDEX IF EXISTS idx_agent_issues_open_title;
--
-- STILL REQUIRED (worker side, NOT deployable from qnfo-ops)
--   * fingerprint (title hash) dedupe check BEFORE the INSERT, so the filer can
--     annotate an existing ticket instead of filing a second one;
--   * a per-run filing cap, so one audit run cannot emit ~110 rows in 30 min;
--   * a dispatch-level guard against the concurrent identical-prompt fan-out
--     (issue 779), which is the actual driver. The index dedupes the symptom;
--     it does not slow the fan-out.
-- ============================================================================
