name = "jnl-reviser"
main = "worker.js"
compatibility_date = "2025-09-01"
workers_dev = true

[[kv_namespaces]]
binding = "STATE"
id = "0cf89b469bcb47058e343611d9117897"

[[services]]
binding = "REF"
service = "jnl-referee"

[ai]
binding = "AI"
