name = "personal-companion"
main = "worker.js"
compatibility_date = "2026-08-01"

[ai]
binding = "AI"

[[services]]
binding = "EMAIL"
service = "qnfo-email"
environment = "production"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "personal-media"

[[d1_databases]]
binding = "PERSONAL"
database_id = "e8d6c61a-10b7-4086-b81e-9e6e85afa407"

[[vectorize]]
binding = "VZ"
index_name = "personal-life"

[[workflows]]
name = "companion-generation"
binding = "GEN_FLOW"
class_name = "GenerationFlow"
schedules = ["0 4,8,12,16,20 * * *"]

[triggers]
crons = ["0 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1
