-- TEXT-QUALITY-LOOP-1 (agent_issues 1895, pillar reach): the fleet's text generators, one row each, with the four fields
-- ENSEMBLE-POLICY-1 asks for: who writes (writer_family), the deterministic check before anything is published or sent
-- (non_model_gate), a reviewer from a different model family that can stop or rewrite the draft (cross_family_read),
-- and the metric that measures the outcome for readers (outcome_metric). 'none' is a recorded gap, not a blank.
-- ran_proof names the D1 table whose rows prove each run; qnfo-fleet-dashboard GET /api/generators reads this table and
-- runs a fixed per-generator query from its own code (GENERATOR_RUNS) to show the latest run. No SQL is read from D1.
-- Source: code read of origin/main 2026-10-05 18:18Z (HEAD 2350cfcf) by session_01KzS1yjXATqG3KDBSEyNTAs; file:line
-- references are in each row's source column. A generator added later gets a row here and an entry in GENERATOR_RUNS.
-- New table, nothing overwritten; rollback: DROP TABLE text_generator_inventory.

CREATE TABLE IF NOT EXISTS text_generator_inventory (
  generator TEXT PRIMARY KEY,
  worker TEXT NOT NULL,
  output TEXT NOT NULL,
  writer_family TEXT NOT NULL,
  non_model_gate TEXT NOT NULL,
  cross_family_read TEXT NOT NULL,
  outcome_metric TEXT NOT NULL,
  ran_proof TEXT NOT NULL,
  gap TEXT,
  source TEXT,
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

INSERT INTO text_generator_inventory (generator, worker, output, writer_family, non_model_gate, cross_family_read, outcome_metric, ran_proof, gap, source) VALUES
('q08-essay', 'q08-signal-engine', 'essays on q08.org/p/',
 'nvidia nemotron-3-120b-a12b, fallback openai gpt-oss-120b (Workers AI directly, not via qnfo-ai)',
 'gate(): length >= 4000, H1/title rules, no handles, banned phrases and headers, overused precedents, invented decimals/IDs/money, no lists or tables, verdict line, full-stop ending; re-run on the edited draft',
 'yes: 2 small judges from families other than the writer (PANEL_POOL: google, meta, alibaba, zai, deepseek), an editor from the other writer family, then a fresh panel; fails open when no judge answers',
 'q08_human_reads_7d, q08_verified_votes_7d; panel agreement q08_panel_effective_votes_30d',
 'q08-signal D1 engine_runs.ran_at; qnfo-audit signals.ts where source = q08 (published pieces)',
 'POST /regen skipped the panel and editor and was open to anyone (Q08-WRITE-ROUTES-TOKEN-1, agent_issues 1995; q08 0.8.6 puts /run and /regen behind x-loop-token)',
 'q08-signal-engine/worker.js:488-494, 650-698, 780, 997-1011, 1117-1137'),
('ask-answer', 'qnfo-ai-search', 'answers streamed on ask.qwav.tech',
 'meta llama-3.3-70b (champion); A/B challengers zai glm-5.3-flash and alibaba qwen3-30b',
 'none before the reader sees the text (tokens stream out); admit() handles rate and spend only; citation checks are measured afterwards',
 'after the fact only: deepseek-v4-flash grounding judge on a 25% sample, not a gate',
 'ask_helpful_rate_30d, ask_grounded_share_7d',
 'qnfo-audit ask_events.ts',
 'no gate before publication (streaming); judge is a sample, not a gate',
 'qnfo-ai-search/worker.js:45, 55, 64, 530, 594, 739, 751, 981-1012'),
('errata-correction', 'errata-hub', 'clarification, acknowledgement and changelog in a published paper, then a new Zenodo version',
 'zai glm-5.3-flash',
 'publishGate(): pipeline_flags.errata_publish_enabled = 1 (off by default, so runs are dry); only drafted low-risk rows publish; stale-version check; AI-disclosure line',
 'yes: google gemma-4-26b-a4b judge on every low-risk draft; fails closed (no verdict or a fail makes it high risk)',
 'none',
 'qnfo-audit errata_actions.created_at (errata_judge_log.created_at for judged drafts)',
 'no outcome metric; a clarification whose quoted sentence is not found is dropped while the acknowledgement still publishes',
 'errata-hub/worker.js:145, 194-336, 21546, 21618-21645'),
('research-paper', 'qnfo-research-exec', 'full papers on Zenodo and papers.qnfo.org',
 'ensemble: openai gpt-oss-120b + zai glm-5.3-flash (x2); short drafts fall back to qnfo-ai auto routing (zai, moonshot, openai, deepseek or the ensemble)',
 'finalGates(): length >= 20000, References heading, no [to verify], enough references, no reasoning preamble; container verification script blocks on mismatch; mathGate blocks only when ops_config research_math_gate = enforce',
 'not guaranteed: review goes to qnfo-ai auto routing, which can pick the writer family; on router failure it runs on glm-5.3-flash (the writer family); advisory after 2 cycles',
 'publications_30d, full_reports_live_30d (volume only)',
 'qnfo-audit research_queue.published_at; cloud_ops_events.ts where job = qnfo-research-exec',
 'review not reliably cross-family (agent_issues 1889 pools); no reader metric',
 'qnfo-research-exec/worker.js:1613-1617, 1714-1761, 2175-2339, 2438-2591, 2717, 2744'),
('social-thread', 'qnfo-social', 'Bluesky threads about papers',
 'deepseek-v4-flash',
 'contentGate() at post time (no q08 links, no mojibake); socialGate() (pause flag, weekly cap); fewer than 3 posts rejected',
 'yes: meta llama-3.3-70b fact checker; fails closed (no verdict leaves a draft)',
 'social_engagement_rate_30d',
 'qnfo-audit social_threads.posted_at (social_learner_posts.posted_at)',
 NULL,
 'qnfo-social/worker.js:69-70, 279-286, 520-580, 808-812, 984, 1030'),
('email-auto-answer', 'qnfo-email-orchestrator', 'short automatic replies to research correspondents',
 'meta llama-3.3-70b',
 'slaGateText(): ASCII only, no links, banned identity words, tone, <= 700 chars, no owner commitments, every number must occur in the incoming mail; slaNoSendReason()',
 'none',
 'inbound_first_response_h_median_30d, inbound_unactioned_72h (speed, not answer quality)',
 'qnfo-audit email_reply_queue.sent_at',
 'no cross-family read; no quality metric',
 'qnfo-email-orchestrator/worker.js:239-254, 336, 391-400, 428, 685-701'),
('idea-question', 'idea-hub', 'research questions listed on ideas.qnfo.org and its RSS',
 'meta llama-3.3-70b (think loop every 6h)',
 'pubQuestion(): blocklist and minimum length; near-duplicate check',
 'none for the public listing (triage scoring by zai and deepseek only routes proposals)',
 'none',
 'qnfo-audit self_questions.ts',
 'no cross-family read; no outcome metric',
 'idea-hub/worker.js:215, 234, 244, 306, 456-483, 513'),
('paper-ask', 'qnfo-gateway', 'answers to POST /api/ask on papers.qnfo.org',
 'meta llama-3.3-70b',
 'none (think-tag stripping and rate limits only)',
 'none',
 'none',
 'none: only aggregate counters ask_rate in qnfo-graph',
 'public model route with no gate, no reviewer, no metric and no per-call row; paper pages now ask through ask.qwav.tech',
 'qnfo-gateway/worker.js:2548-2603, 3545, 3614'),
('patent-disclosure', 'qnfo-ipatent', 'patent disclosure draft returned to the inventor (/api/draft)',
 'openai gpt-oss-120b, falling back to zai glm-5.3-flash, then deepseek-v4-flash',
 'at least 3 of 7 required section headings, otherwise the next model is tried; daily cap and rate limit',
 'none',
 'ipatent_drafters_7d (usage only)',
 'ipatent-db submissions.created_at (not in qnfo-audit)',
 'no cross-family read; no quality metric; run proof outside qnfo-audit',
 'qnfo-ipatent/worker.js:18-22, 393-494, 639-678, 2181'),
('paper-revision', 'qnfo-paper-reviser', 'AI edits to published papers, deposited as v2.0.0',
 'deepseek-v4-flash',
 'an edit applies only if its quoted text is found; only low-severity edits; output sanity check; then research-exec qualityGate before publishing',
 'none',
 'none',
 'qnfo-audit paper_revision_log.created_at (version_queue.created_at)',
 'no cross-family read; no outcome metric',
 'qnfo-paper-reviser/worker.js:6, 222-295, 413-471, 1055-1059'),
('companion-essay', 'personal-companion', 'essays emailed to the owner and confirmed subscribers (reading.q08.org)',
 'deepseek-reasoner and deepseek-chat (DeepSeek API, personal key, outside qnfo-ai)',
 'validatePiece(): word count, banned words, emoji, title, objection; similarExists() duplicate check',
 'none: the critic is deepseek-chat, the writer family',
 'none',
 'qnfo-audit signals.ts where source = reading (personal-life companion_runs.run_at)',
 'critic is same-family; no outcome metric',
 'personal-companion/worker.js:20-24, 1050, 1096-1146, 1176-1240, 1587'),
('ideas-public-threads', 'qnfo-ai + idea-hub', 'chat answers published as transcripts on ideas.qnfo.org',
 'the model the chat client asks for; qnfo/auto goes through the route pools or the ensemble',
 'qnfo-ai _isPublicRow() (no empty, classifier JSON, reasoning dump, fallback, machine user agent or probe); idea-hub publicTitle() and blocked()',
 'only when the call ran the qnfo-ai ensemble (validator deepseek-v4-flash); not a gate',
 'none',
 'qnfo-audit chat.ts (cloud_ops_events kind = ensemble-run for ensemble calls)',
 'no gate-level cross-family read; no outcome metric',
 'qnfo-ai/worker.js:863, 1048-1066, 1612, 2209, 2502-2506; idea-hub/worker.js:216, 228');
