-- TRANSFORMATION-LOOP-1 (2026-10-06, pillar: autonomy; owner directive 2026-10-06: a continuing program of transformational
-- change, systemwide, fully automatic and 100% autonomous). docs/TRANSFORMATION-PROGRAM.md (TRANSFORMATION-PROGRAM-1) is the
-- audit and the plan; qnfo-fleet-control 0.4.131 is the engine (transformationTick, hourly). This file seeds the engine's
-- registers from the document: one transformation_levers row per lever with its kind (code = a single-file edit the code
-- loop can land; refactor, retire, migration, platform, repo, verify, config; owner = the owner's list, never dispatched),
-- its wave (section 4), its path and anchor where the edit point is known, and the child issue the program's author
-- already filed (adopted, never duplicated). Status seeds: landed where the evidence exists today (named in note),
-- dispatched where a code task is in flight, session where a session-task issue exists, pending otherwise. The loop
-- maintains every row from here on. Also: the merge runner's trusted-origin list gains the program's two origins (backup
-- key kept), the loop's metric and trigger, and a contract on the loop's heartbeat. Idempotent; applied by the session
-- that wrote it. Rollback: DROP TABLE transformation_levers; DROP TABLE transformation_runs; restore ops_config
-- code_merge_trusted_sources from code_merge_trusted_sources--bak-20261006T0730Z; DELETE FROM analytics_metric_triggers
-- WHERE metric_key='transformation_levers_landed_14d'; DELETE FROM metric_registry WHERE metric='transformation_levers_landed_14d';
-- DELETE FROM remediation_contracts WHERE class='transformation-loop-1'.

CREATE TABLE IF NOT EXISTS transformation_levers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tp INTEGER NOT NULL,
  n INTEGER NOT NULL,
  key TEXT NOT NULL,
  title TEXT NOT NULL,
  kind TEXT NOT NULL,
  wave TEXT NOT NULL,
  pillar TEXT,
  path TEXT,
  anchor TEXT,
  detail TEXT,
  dod TEXT,
  issue_id INTEGER,
  code_task_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  note TEXT,
  dispatched_at TEXT,
  landed_at TEXT,
  verified_at TEXT,
  stalled_at TEXT,
  updated_at TEXT,
  UNIQUE(tp, n)
);
CREATE TABLE IF NOT EXISTS transformation_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts TEXT,
  worker_version TEXT,
  wave TEXT,
  levers_json TEXT,
  scoreboard_json TEXT,
  actions_json TEXT
);

-- T1 Autonomy engine (RM-TP-1-AUTONOMY-ENGINE, epic 2004)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (1, 1, 'trusted-origin-parity', 'The merge runner trusts every origin the planner trusts', 'code', 'W0', 'autonomy', 'qnfo-fleet-control/worker.js', 'function cmTrusted(source, title, list) {', 'cmTrusted accepts the same (source, title-prefix) pairs the code orchestrator planner accepts (METRIC-TRIGGER-, REACH-IDEA-, TP-), read from one shared list.', 'no code_tasks row ends failed with last_error like merge-runner:%not a trusted origin% for a planner-created issue over 14 days', 2005, 'dispatched', 'adopted: issue 2005 carries the code-task line; code task ct_u4ih8uzgsfxzvm branch_pushed 2026-10-06T07:00Z, merge_state rejected by a session review at 07:12Z (the patch trusted qnfo-code-orchestrator pairs; the issues come from qnfo-fleet-control). The first tick flips this lever to session (T1 lever 12) and files CODE-TASK-NEEDS-SESSION-1: a control-plane edit a session merges until T1.8', '2026-10-06T06:00:00Z', NULL),
 (1, 2, 'pr-open-on-20min-tick', 'fleet-control opens PRs for branch_pushed code tasks on the */20 tick (replaces: orchestrator pushes its own branch)', 'code', 'W0', 'autonomy', 'qnfo-fleet-control/worker.js', NULL, 'code-task-publish pushes the branch within a minute; the PR was opened only by the hourly merge tick (40-50 min, 5 h overnight). The */20 branch also runs codeMergeTick(env, { openOnly: true }).', 'median minutes from ready_to_publish to pr_opened_at under 15 over 14 days', 2017, 'landed', 'PR 667 merged 2026-10-06T06:51Z (4ed2900): qnfo-fleet-control 0.4.130 PR-OPEN-ON-20MIN-TICK-1, live at 07:05Z (/health 0.4.130-pr-open-20min); issue 2017 closes on its own probe', '2026-10-06T06:41:00Z', '2026-10-06T06:51:04Z'),
 (1, 3, 'rebase-before-publish', 'Rebase-before-publish: re-anchor against current main before the push and retry once on stale base or patch does not apply', 'code', 'W0', 'autonomy', 'qnfo-code-orchestrator/worker.js', NULL, 'Seven closures named stale base or patch does not apply.', 'no code_tasks row ends with last_error naming stale base or does not apply over 14 days', NULL, 'pending', NULL, NULL, NULL),
 (1, 4, 'anchor-repair', 'An anchor that occurs 0 or 2 times is repaired by the model, not parked as needs_human', 'code', 'W0', 'autonomy', 'qnfo-code-orchestrator/worker.js', NULL, 'Ask the model once for a replacement anchor from the current file; park only after the repaired anchor also fails.', 'code_tasks rows with last_error like %anchor% ending needs_human = 0 over 14 days', 2007, 'session', 'adopted: issue 2007 (session-task after the code loop paraphrased a string literal instead)', '2026-10-06T06:41:00Z', NULL),
 (1, 5, 'container-verifier', 'Every code task runs the worker suites and the deploy gate in the PyContainer before a PR', 'code', 'W0', 'autonomy', 'qnfo-code-orchestrator/worker.js', NULL, 'node --check, the changed worker''s *.test.mjs and scripts/deploy_gate.py --check inside the container; a failure is one more propose round, not a PR.', '0 code-loop PRs fail the gate over 14 days and no task ends no-verifier', 2008, 'session', 'adopted: issue 2008 (session-task)', '2026-10-06T06:27:00Z', NULL),
 (1, 6, 'merges-per-tick-3', 'code_merge_max_merges_per_tick reads 3 in ops_config', 'config', 'W0', 'autonomy', NULL, NULL, 'Raise to 5 only when the queue holds green PRs at tick time.', 'ops_config code_merge_max_merges_per_tick = 3', NULL, 'landed', 'ops_config code_merge_max_merges_per_tick = 3 read live 2026-10-06T07:05Z', NULL, '2026-10-06T07:05:00Z'),
 (1, 7, 'evolve-parse-gate', 'A candidate that does not parse is re-asked once with the parse error; evolve_parse_pass_pct_7d is graded', 'code', 'W0', 'autonomy', 'qnfo-fleet-control/worker.js', NULL, '93 of 120 evolve candidates were rejected-parse.', 'evolve_parse_pass_pct_7d registered and >= 50', NULL, 'pending', NULL, NULL, NULL),
 (1, 8, 'branch-protection-control-plane', 'GitHub branch protection on main with the required checks, then drop CONTROL-PLANE-MANUAL-1 and shrink CM_DENY for fully green heads', 'platform', 'W1', 'autonomy', 'qnfo-fleet-control/worker.js', NULL, 'The platform, not the policy, becomes the gate; control-plane changes keep the stricter test set (T5.4). The loop treats every control-plane code lever as a session lever until this lands.', 'main protected with gate, guard, mirror-guard, comparator, charter and test required; at least 10 control-plane PRs merged by the loop', NULL, 'pending', NULL, NULL, NULL),
 (1, 9, 'code-task-lines-on-triggers', 'Every enabled trigger whose lever is a single-file change carries code-task and code-anchor lines (ACT-BRIDGE-1)', 'migration', 'W0', 'autonomy', 'migrations', NULL, 'The 69 triggers without a line are reviewed in analytics_metric_triggers.action by one migration.', 'breach_code_task_pct >= 30', NULL, 'pending', NULL, NULL, NULL),
 (1, 10, 'orphan-suites-into-gate', 'The 19 suites no workflow references join the gate through one suite runner', 'repo', 'W1', 'autonomy', '.github/workflows/deploy-gate.yml', NULL, 'scripts/run-suites.mjs runs every *.test.mjs of the changed workers (T3.8).', 'every *.test.mjs in the repo is run by a workflow on every PR', NULL, 'pending', NULL, NULL, NULL),
 (1, 11, 'multi-file-tasks', 'Multi-file code tasks: the task carries a file list and the agent edits a branch checkout in the container', 'refactor', 'W3', 'autonomy', 'qnfo-code-orchestrator/worker.js', NULL, 'The more-than-one-file refusal becomes more-than-the-task''s-file-list.', 'a code task with two files reaches a merged PR', NULL, 'pending', NULL, NULL, NULL),
 (1, 12, 'session-fallback', 'A task that fails twice files CODE-TASK-NEEDS-SESSION-1 with the failure text; the watchmaker index counts those rows', 'code', 'W0', 'autonomy', 'qnfo-fleet-control/worker.js', NULL, 'TRANSFORMATION-LOOP-1 (qnfo-fleet-control 0.4.131) files the row when a dispatched lever''s code tasks all ended failed, needs_human or closed; qnfo-fleet-dashboard WATCHMAKER_OPS transformation-loop counts the open rows.', 'an open CODE-TASK-NEEDS-SESSION-1 row raises watchmaker_index; none open means no session dependence', NULL, 'pending', 'in PR 662 (session_01CX4ooVZuEie1F9eEtYHx2u); lands when qnfo-fleet-control 0.4.131 is live', NULL, NULL),
 (1, 13, 'noop-proposal-gate', 'The code orchestrator refuses a proposal that changes only string literals or comments and runs one more propose round', 'code', 'W0', 'autonomy', 'qnfo-code-orchestrator/worker.js', NULL, 'Two TP-1 tasks returned a 2-line paraphrase of a string literal plus the VERSION bump and passed the verifier.', 'no merged code-loop PR whose non-VERSION diff touches only string literals or comments over 14 days', 2018, 'landed', 'PR 666 merged 2026-10-06T06:42Z (4b03a30): qnfo-code-orchestrator 0.3.17 NOOP-PROPOSAL-GATE-1, live (/health 0.3.17-noop-gate); issue 2018 closes on its own probe', '2026-10-06T06:41:00Z', '2026-10-06T06:42:49Z');

-- T2 One kernel, one dispatcher, heartbeats (RM-TP-2-ONE-KERNEL, epic 2009)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (2, 1, 'retire-kaizen-skill-sync-outreach', 'Retire qnfo-kaizen, qnfo-skill-sync and qnfo-outreach (WORKER-RETIRE-WAVE-2)', 'retire', 'W0', 'core', NULL, NULL, 'Standing grant, dependency check first.', 'the three scripts are absent from the account and their directories carry RETIRED', NULL, 'landed', 'PR 657 merged 2026-10-06 (a15af7d); scripts deleted; dangling KAIZEN/SKILLSYNC bindings removed from qnfo-ops the same morning (cf-ops-actions runs 37423611040, 37423655727)', NULL, '2026-10-06T06:11:00Z'),
 (2, 2, 'fold-email-orchestrator-scorer-indexer', 'Fold qnfo-email-orchestrator, qnfo-autonomy-scorer and qnfo-paper-indexer into their hosts; then qnfo-backlog-exec, qnfo-observability, qnfo-lifecycle, qnfo-ai-calibration into ai-health-prober', 'retire', 'W0', 'core', NULL, NULL, 'FOLD-WAVE-1 (PR 668, session 013sMN) carries the first three; the rest follow under the standing grant with a dependency check each.', 'worker_count <= 34 from this theme', NULL, 'landed', 'FOLD-WAVE-1 PR 668 merged 2026-10-06T07:16Z (d984bb4): qnfo-email-orchestrator, qnfo-autonomy-scorer (into qnfo-observability, SCORER-FOLD-1) and qnfo-paper-indexer carry FOLDED; qnfo-ops 2.38.44-indexer-fold live', '2026-10-06T06:50:00Z', '2026-10-06T07:16:28Z'),
 (2, 6, 'fold-wave-2', 'Fold qnfo-backlog-exec, qnfo-observability, qnfo-lifecycle and qnfo-ai-calibration into ai-health-prober; fleet-exec and qnfo-paper-reviser into their hosts (FOLD-WAVE-2)', 'retire', 'W1', 'core', NULL, NULL, 'The second half of T2.2 under the standing grant, a dependency check per worker (binders, URL callers, live readers of the tables only it writes).', 'worker_count <= 32', NULL, 'session', 'in flight: at 2026-10-06T07:19Z GET /work-locks listed live claims on qnfo-observability/worker.js, fleet-exec/FOLDED, qnfo-paper-reviser/FOLDED and qnfo-research-exec/worker.js (expiring 08:24-08:56Z)', '2026-10-06T07:19:00Z', NULL),
 (2, 3, 'one-probe-pass', 'One probe pass: fleet-control''s */20 tick probes every live worker once into worker_live_audit; the dashboard, lifecycle and deploy-guard read that table', 'code', 'W1', 'core', 'qnfo-fleet-control/worker.js', NULL, 'RM-PROBE-VERIFIED-COVERAGE-1 content assertions ride the same pass.', 'requests on workers with no public route under 3,000 a day', NULL, 'pending', NULL, NULL, NULL),
 (2, 4, 'heartbeats-every-cron', 'Every cron handler ends with one fleet_heartbeat upsert; the monitor of monitors flags any worker silent for 2x its cadence', 'refactor', 'W1', 'core', NULL, NULL, 'A 3-line helper in every cron worker (RM-MONITOR-THE-MONITORS-1).', 'every cron worker has a fleet_heartbeat row younger than 2x its cadence', NULL, 'pending', NULL, NULL, NULL),
 (2, 5, 'fleet-exec-single-dispatcher', 'fleet-exec */10 becomes the single dispatcher for every schedule finer than hourly; workers keep at most one platform cron each', 'code', 'W1', 'core', 'fleet-exec/worker.js', NULL, 'C5 convergence (#1691).', 'cron_schedules <= 44', NULL, 'pending', NULL, NULL, NULL);

-- T3 Footprint teardown (RM-TP-3-FOOTPRINT-TEARDOWN, epic 2010)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (3, 1, 'retire-agent-orchestrator-archive', 'Retire qnfo-agent-orchestrator (idea-hub''s binding moves) and qnfo-archive (handoff search joins memory-mcp)', 'retire', 'W2', 'core', NULL, NULL, 'qnfo-outreach landed with T2.1; qnfo-email-orchestrator folds with T2.2; WORKER-RETIRE-WAVE-3 claims qnfo-agent-orchestrator.', 'both scripts absent from the account with RETIRED markers', NULL, 'session', 'WORKER-RETIRE-WAVE-3 claimed by session 013sMN 2026-10-06', '2026-10-06T07:00:00Z', NULL),
 (3, 2, 'mcp-two-to-one', 'MCP 2 -> 1: qnfo-memory-mcp''s tools join qnfo-tools-mcp behind one authenticated endpoint', 'refactor', 'W2', 'core', 'qnfo-tools-mcp/worker.js', NULL, 'T8.1 fixes the missing auth at the same time.', 'one MCP worker serves tools, memory, skills and search', NULL, 'pending', NULL, NULL, NULL),
 (3, 3, 'radars-into-research-exec', 'radar-hub''s modules move into qnfo-research-exec''s scheduled handler as stages', 'refactor', 'W2', 'core', 'qnfo-research-exec/worker.js', NULL, 'Conference and events radars keep writing their tables; JOB_MARKET_WATCH retires.', 'radar-hub carries a FOLDED marker and every radar table still fills', NULL, 'pending', NULL, NULL, NULL),
 (3, 4, 'errata-hub-decision', 'errata-hub de-minified or retired by its 30-day external-row rule', 'refactor', 'W2', 'core', 'errata-hub/worker.js', NULL, 'If errata_queue gains no external row in 30 days, retire with a RETIRED marker and leave the public errata pages to qnfo-gateway.', 'decision recorded on epic 2010 with the errata_queue count', NULL, 'pending', NULL, NULL, NULL),
 (3, 5, 'one-email-transport', 'The 8 private send_email bindings route through qnfo-email''s /send (one audit trail, one kill switch, one suppression list)', 'refactor', 'W1', 'core', 'qnfo-email/worker.js', NULL, 'Eight workers each hold a send_email binding while six route through qnfo-email.', 'one send_email binding in the account outside qnfo-email', NULL, 'pending', NULL, NULL, NULL),
 (3, 6, 'd1-ten-to-eight', 'D1 10 -> 8: qnfo-cms and portfolio-state fold into qnfo-audit after verified copies (D1-FOLD-1)', 'migration', 'W2', 'core', NULL, NULL, 'qnfo-outreach stays until the outreach consolidation lands; qnfo-identity stays by design.', 'd1_databases = 8', NULL, 'pending', NULL, NULL, NULL),
 (3, 7, 'qnfo-audit-retention', 'qnfo-audit retention: bak_* tables older than 30 days dropped after an R2 dump; a table_registry row per table family; the lifecycle tick enforces retention', 'migration', 'W2', 'core', 'qnfo-lifecycle/worker.js', NULL, '410 tables, growing about 10 MB a day.', 'qnfo-audit size not growing week over week', NULL, 'pending', NULL, NULL, NULL),
 (3, 8, 'archive-and-appliers', 'RETIRED/FOLDED and toml-less directories move under archive/ with a manifest; spent apply-* and restore-container-config* workflows deleted; one suite runner replaces the 108 gate steps', 'repo', 'W0', 'core', '.github/workflows', NULL, 'TP-3a classifies the 40 workflows first (issue 2019).', 'workflow count <= 25 and the live tree holds live directories only', 2019, 'session', 'adopted: issue 2019 (session-task)', '2026-10-06T06:45:00Z', NULL),
 (3, 9, 'charter-pillar-on-every-toml', 'charter-guard.py requires # charter-pillar: on every live wrangler.toml, with the 42 declarations landed in the same PR', 'repo', 'W1', 'core', 'scripts/charter-guard.py', NULL, 'Today 2 of 42 declare a pillar.', 'charter-guard fails on a live wrangler.toml without a pillar line', NULL, 'pending', NULL, NULL, NULL);

-- T4 Cost (RM-TP-4-COST-FLEET-40, epic 2011)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (4, 1, 'cost-lines-split', 'unified_cost_usd_30d splits into fleet, session and owner-client lines; the cap check reads the fleet line', 'code', 'W1', 'cost', 'qnfo-fleet-control/worker.js', NULL, 'RM-COST-UNIFIED-SPEND-1; session callers are gateway metadata session:*; owner-client spend is declared.', 'session_ai_spend_30d_usd and owner_client_spend_30d_usd registered; the cap reads fleet_ai_run_rate_30d_usd', NULL, 'pending', NULL, NULL, NULL),
 (4, 2, 'prefix-caching', 'Prefix caching on the three paid paths with cache_read_tokens written to ai_spend_ledger', 'code', 'W1', 'cost', 'qnfo-ai/worker.js', NULL, 'RM-COST-PREFIX-CACHE-1: the stable prefix goes first.', 'cache_read_tokens > 0 on each paid path', NULL, 'pending', NULL, NULL, NULL),
 (4, 3, 'draft-verify-ladder', 'Draft-verify ladder on every paid path: free draft, cheap verify, paid repair only on FAIL', 'code', 'W2', 'cost', 'qnfo-ai/worker.js', NULL, 'RM-COST-L6-DRAFT-VERIFY-1; the ensemble validator budget (5.31.5) is the first instance.', 'every paid path records a draft-verify verdict', NULL, 'pending', NULL, NULL, NULL),
 (4, 4, 'one-prober', 'One prober, hourly, 1-token non-reasoning pings (canary and prober cost)', 'retire', 'W2', 'cost', 'ai-health-prober/worker.js', NULL, 'PROBER-FOLD-1 (PR 668) runs the prober inside qnfo-ai-calibration first.', 'one prober worker, under 30 model calls an hour', NULL, 'landed', 'PROBER-FOLD-1 in PR 668 merged 2026-10-06T07:16Z (d984bb4): the prober runs inside qnfo-ai-calibration; the 1-token ping cadence is T4.4''s remaining half, graded by the prober-cost line', '2026-10-06T06:50:00Z', '2026-10-06T07:16:28Z'),
 (4, 5, 'cheaper-model-switches', 'Cheaper-model switches with per-request fallback and automatic revert on q08 compose and the research reviewer (PERF_LEVERS)', 'code', 'W2', 'cost', 'q08-signal-engine/worker.js', NULL, 'TWIN-FLASH-1 is the pattern; recorded on the issues.', 'fleet_ai_run_rate_30d_usd <= 40 for 14 days', NULL, 'pending', NULL, NULL, NULL),
 (4, 6, 'sessions-through-governor', 'The qnfo-ai /spend governor caps session callers at a separate budget', 'code', 'W2', 'cost', 'qnfo-ai/worker.js', NULL, 'A session cannot push the fleet over its cap.', 'session callers carry their own governor budget in GET /spend', NULL, 'pending', NULL, NULL, NULL);

-- T5 Measurement to actuation (RM-TP-5-MEASURE-TO-ACT, epic 2012)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (5, 1, 'code-task-lines-every-trigger', 'code-task lines on every trigger whose lever is one file', 'migration', 'W0', 'autonomy', 'migrations', NULL, 'The same lever as T1.9.', 'breach_code_task_pct >= 30', NULL, 'superseded', 'tracked as T1.9', NULL, NULL),
 (5, 2, 'probe-generator', 'Probe generator in fleet-control: a needs-machine-probe contract whose issue names a metric or a table and threshold gets a d1-query probe automatically, marked generated', 'code', 'W1', 'autonomy', 'qnfo-fleet-control/worker.js', NULL, '91 open contracts are the first batch.', 'remediation_contracts WHERE status=needs-machine-probe = 0', NULL, 'pending', NULL, NULL, NULL),
 (5, 3, 'migration-runner', 'The lifecycle tick applies migrations/*.sql with an APPLY-BY: lifecycle header and a rollback block, records migration_runs', 'code', 'W1', 'autonomy', 'qnfo-lifecycle/worker.js', NULL, 'Never applies a file without a rollback block.', 'a migration with the header is applied by the tick within 24h of merge', NULL, 'pending', NULL, NULL, NULL),
 (5, 4, 'control-plane-test-set', 'The gate runs the full suite set for the control-plane workers and the changed worker''s set otherwise', 'repo', 'W1', 'autonomy', '.github/workflows/deploy-gate.yml', NULL, 'So T1.8 can open the control plane to the loop.', 'a control-plane PR runs every suite; another runs only its worker''s', NULL, 'pending', NULL, NULL, NULL),
 (5, 5, 'security-metric-graded', 'security_open_issues counts every security finding, not only SEC-* titles', 'code', 'W0', 'security', 'qnfo-fleet-control/worker.js', 'security_open_issues: { pillar: "security", target: "0 (open SEC-* or category security issues)" }', 'Count open issues whose title starts with SEC-, whose category is security, or whose title matches UNAUTHENTICATED|STATIC-TOKEN|CREDENTIAL|EXPOSED|TOKEN-1.', 'the metric reads the true count and the pillar health reflects it', 2013, 'dispatched', 'adopted: issue 2013 carries the code-task line (control-plane path: a session merges the PR until T1.8)', '2026-10-06T06:00:00Z', NULL),
 (5, 6, 'blocked-external-state', 'An open issue whose next step is an owner decision, a third party or another loop records that disposition in issue_triage.remediation', 'data', 'W0', 'autonomy', NULL, NULL, 'blocked-external: <who> <what>; default in effect: <x>; reopen trigger: <y>, or self-closing: <worker> <condition>. The scorer already counts a triage remediation as a next action.', 'every open issue has a next action or a recorded disposition (ooda_decide >= 4.5)', NULL, 'landed', 'done 2026-10-06 for issues 1750, 1898, 1901, 1903 (blocked-external) and 2002 (self-closing); document 1.1 T5 lever 6', NULL, '2026-10-06T07:15:13Z'),
 (5, 7, 'freshness-measures', 'freshness_guard grades only live producers and only rows re-checked within 48 hours; event-driven tables graded as events', 'code', 'W0', 'autonomy', 'qnfo-ai-calibration/worker.js', NULL, 'Drop signals whose producer is RETIRED or FOLDED (kaizen), grade version_queue as an event, reconcile the probe roster with ai_model_health, and in the scorer (qnfo-observability after SCORER-FOLD-1) count only rows re-checked within 48 hours, reporting the rest as unmeasured (handoffs, vault_notes_index). ooda_observe read 3.8 on 2026-10-06 (13 of 17 fresh).', 'ooda_observe >= 4.5 with every counted row re-checked within 48 hours', 2026, 'session', 'adopted: issue 2026 (two files, the checker and the scorer host: a session, or the code loop once T1.11 lands)', '2026-10-06T07:15:00Z', NULL),
 (5, 8, 'watchmaker-inverted-measured', 'watchmaker_inverted is measured from watchmaker_index in the daily scoring, replacing the hand score', 'code', 'W0', 'autonomy', 'qnfo-observability/worker.js', NULL, 'scorerMod inside qnfo-observability (SCORER-FOLD-1): write 5 x (1 - counted / ops measured) from the latest watchmaker_runs row with the counted ops in the evidence. The hand score reads 4.8 from 2026-09-24, past its next date; the measured value is expected to read lower (3 counted ops on 2026-10-06), an honest correction.', 'the latest watchmaker_inverted row is MEASURED and dated today', 2027, 'session', 'adopted: issue 2027; the host file carried a live work claim at 07:19Z (qnfo-observability/worker.js, fold-wave session), so it lands with or after FOLD-WAVE-2', '2026-10-06T07:15:00Z', NULL),
 (5, 9, 'blocked-external-on-dashboard', 'The dashboard lists blocked-external rows under the owner''s queue with their default in effect', 'code', 'W1', 'autonomy', 'qnfo-fleet-dashboard/worker.js', NULL, 'The later code half of T5 lever 6: issue_triage.remediation rows beginning blocked-external: shown with their default and reopen trigger.', 'fleet.qnfo.org lists every blocked-external issue with its default', NULL, 'pending', NULL, NULL, NULL);

-- T6 Durable execution (RM-TP-6-DURABLE-EXECUTION, epic 2014)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (6, 1, 'ops-agent-workflow', 'The ops agent promotes a run that exceeds its interactive budget to a Workflow with checkpointed continuation', 'refactor', 'W2', 'autonomy', 'qnfo-ops/worker.js', NULL, 'RM-DURABLE-AGENT-EXECUTION-1 (#1680).', 'ops_tool_budget_bail 0 in 7 days', NULL, 'pending', NULL, NULL, NULL),
 (6, 2, 'research-pipeline-workflow', 'The research pipeline''s stages become one Workflow per version request; the */15 drain remains as the dispatcher', 'refactor', 'W3', 'autonomy', 'qnfo-research-exec/worker.js', NULL, 'ground, draft, review, revise, publish, PDF, graph, related links.', 'a version request runs as one Workflow instance end to end', NULL, 'pending', NULL, NULL, NULL),
 (6, 3, 'code-tasks-workflow', 'Code tasks run as a Workflow (fetch, edit, test, publish, merge, verify) so a failed step resumes', 'refactor', 'W3', 'autonomy', 'qnfo-code-orchestrator/worker.js', NULL, NULL, 'a code task resumes from its failed step without restarting', NULL, 'pending', NULL, NULL, NULL),
 (6, 4, 'metric-events-queue', 'Breach and recovery events from the metric loop publish to a Queue the dashboards and the code loop consume', 'code', 'W3', 'autonomy', 'qnfo-fleet-control/worker.js', NULL, 'Replaces the hourly re-reads.', 'a breach reaches the code loop within one queue delivery', NULL, 'pending', NULL, NULL, NULL);

-- T7 Reach that survives the review gate (RM-TP-7-REACH-REVIEW-GATE, epic 2015)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (7, 1, 'subscribe-box-every-surface', 'A subscribe box on every public surface posting to the double opt-in with source=<surface>; RM-SUBSCRIBE-CTA-1 marked built', 'code', 'W0', 'reach', 'idea-hub/worker.js', NULL, 'Live on qnfo.org and papers.qnfo.org; ideas.qnfo.org in #2001; missing on ipatent.qnfo.org and ask.qwav.tech.', 'every public surface carries the box and RM-SUBSCRIBE-CTA-1 reads built', 2001, 'session', 'adopted: REACH-IDEA-1 subscribe-box on ideas (issue 2001) in flight by session 01KzS1; ask.qwav.tech landed in qnfo-ai-search 2.2.6 (PR 669 merged 2026-10-06T07:10Z, 88b14fc); ipatent.qnfo.org remains', '2026-10-06T05:44:00Z', NULL),
 (7, 2, 'scholar-pdf-coverage', 'scholar_pdf_coverage_pct measured and the missing PDFs rendered so citation_pdf_url is on every paper page', 'code', 'W1', 'reach', 'qnfo-paper-indexer/worker.js', NULL, 'citation_pdf_url is emitted only when the paper record carries a PDF (STRATEGY s4).', 'scholar_pdf_coverage_pct registered and >= 95', NULL, 'pending', NULL, NULL, NULL),
 (7, 3, 'funnel-monitor', 'Funnel monitor: one daily row per stage (publication, deposit, page views, posts, engagement, subscriptions) in reach_signals, graded as funnel_conversion_30d', 'code', 'W1', 'reach', 'qnfo-fleet-dashboard/worker.js', NULL, 'RM-FUNNEL-E2E-MONITOR-1.', 'funnel_conversion_30d registered with a trigger', NULL, 'pending', NULL, NULL, NULL),
 (7, 4, 'monthly-note-linkedin-series', 'Monthly research note to subscribers from the selected works; LinkedIn document-post series through Buffer inside the cadence caps', 'code', 'W1', 'reach', 'qnfo-subscribers/worker.js', NULL, 'Replaces the weekly auto-digest once 10+ subscribers.', 'one monthly note sent from the selected works; subscribers_growth_monthly >= 5', NULL, 'pending', NULL, NULL, NULL),
 (7, 5, 'arxiv-endorsement-orcid', 'arXiv endorsement for works 1, 2, 4 and ORCID entries', 'owner', 'W1', 'reach', NULL, NULL, 'Owner-held (STRATEGY s4, charter s7 owner list); recorded, never on the critical path.', 'arXiv listing for a selected work (a credibility event)', NULL, 'pending', 'owner-held: listed, never dispatched', NULL, NULL);

-- T8 The trust boundary (RM-TP-8-TRUST-BOUNDARY, epic 2016)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (8, 1, 'memory-mcp-auth-verified', 'qnfo-memory-mcp''s MCP_TOKEN gate proven by an unauthenticated probe suite and #1678 closed on it', 'verify', 'W0', 'security', 'qnfo-memory-mcp/worker.js', NULL, 'Live in 2.0.5: 401 without a bearer, 503 when unset.', '#1678 closed with the probe as evidence', 1678, 'landed', 'issue 1678 closed 2026-10-06', NULL, '2026-10-06T06:00:00Z'),
 (8, 2, 'containers-exec-access', 'qnfo-containers-pilot /exec behind Access service tokens or a rate limit; token rotation scripted', 'code', 'W2', 'security', 'qnfo-containers-pilot/worker.js', NULL, '#1677.', 'an unauthenticated POST /exec returns 401 or 403 and the token rotates by script', 1677, 'pending', 'issue 1677 closed before the lever landed: re-verify by probe', NULL, NULL),
 (8, 3, 'access-and-waf', 'Access applications on /ops/*, /run, /work-lock/* and dashboard writes; WAF rate limits on the idea form, email command route and ask endpoints', 'platform', 'W2', 'security', NULL, NULL, 'One-time platform steps through cf-ops-actions, recorded.', 'unauthenticated probes of every write route return 401 or 403 (a suite)', NULL, 'pending', NULL, NULL, NULL),
 (8, 4, 'secrets-store', 'Secrets Store adoption with a rotation runbook executed by cf-ops-actions', 'platform', 'W3', 'security', NULL, NULL, 'RM-SECRETS-STORE-1.', 'every worker secret is a Secrets Store reference with a rotation date', NULL, 'pending', NULL, NULL, NULL),
 (8, 5, 'tail-worker', 'A Tail Worker writing unsampled exceptions to worker_logs', 'refactor', 'W3', 'security', NULL, NULL, 'RM-TAIL-WORKERS-1; needs a new worker, so it names its net-zero retirement.', 'every exception in 24h has a worker_logs row', NULL, 'pending', NULL, NULL, NULL);

-- T9 A deploy path that cannot lock itself out (document 1.1; RM-TP-9-DEPLOY-NO-LOCKOUT, epic 2025)
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (9, 1, 'delete-after-unbind', 'cf-ops-actions delete-worker refuses while any live service binding targets the worker, naming the binders (DELETE-AFTER-UNBIND-1)', 'repo', 'W0', 'core', 'scripts/cf_ops_actions.py', NULL, 'PR 657 deleted qnfo-kaizen and qnfo-skill-sync while three live bindings still pointed at them: Cloudflare refused qnfo-ops and the dashboard with error 10143 from 06:11Z (GitHub #660).', 'delete-worker refuses a bound worker; scripts/cf_ops_delete_worker_test.py runs in the gate', NULL, 'landed', 'PR 670 merged 2026-10-06T07:15Z (8a501ce): scripts/cf_ops_actions.py reads every live script''s bindings first; scripts/cf_ops_delete_worker_test.py in deploy-gate', NULL, '2026-10-06T07:15:13Z'),
 (9, 2, 'prune-accepts-10143', 'The deploy prune accepts error 10143 as well as 10144 (DANGLING-BINDING-PRUNE-1)', 'code', 'W0', 'core', 'qnfo-ops/worker.js', NULL, NULL, 'a dangling binding refused with 10143 is pruned by the canonical deploy', NULL, 'landed', 'qnfo-ops 2.38.43-dangling-10143 deployed 2026-10-06 (cf-ops-actions run 37423700798); 2.38.44-indexer-fold live at 07:05Z', NULL, '2026-10-06T06:27:00Z'),
 (9, 3, 'deployer-fallback', 'canonical-deploy.yml runs the code-only bootstrap once when /ops/deploy fails for qnfo-ops itself and records which path landed in fleet_deploys', 'repo', 'W1', 'core', '.github/workflows/canonical-deploy.yml', NULL, 'qnfo-ops deploys itself through its own live code; on 2026-10-06 its fix could not ship until the bindings were removed out of band. deploy-qnfo-ops.yml and scripts/raw_put.py exist but no loop takes them.', 'a forced /ops/deploy failure for qnfo-ops lands through the bootstrap path with a fleet_deploys row naming the path', NULL, 'pending', NULL, NULL, NULL),
 (9, 4, 'dangling-bindings-census', 'A daily census of dangling service bindings written to worker_live_audit and registered as dangling_bindings with its trigger', 'code', 'W0', 'core', 'qnfo-fleet-control/worker.js', NULL, 'Every script''s /settings (the read used on 2026-10-06) on the daily tick; the metric and its trigger land in one migration (METRIC-CLOSED-LOOP-1). The scoreboard already carries dangling_bindings, unmeasured until this lands.', 'metric_registry.dangling_bindings measured daily and 0', NULL, 'pending', NULL, NULL, NULL);

-- Issue 1677 is closed although its lever has not landed: the loop would land it on the closed issue. Decouple so the lever
-- is re-verified by probe (T8.3's suite), not assumed.
UPDATE transformation_levers SET issue_id = NULL WHERE tp = 8 AND n = 2;

-- The merge runner's trusted-origin list gains the program's two origins: the engine files TP-* issues as qnfo-fleet-control,
-- the program's author filed the epics as TRANSFORMATION-PROGRAM-1. Same trust as METRIC-TRIGGER- and REACH-IDEA- (kernel
-- loops). Backup of the previous value kept under its own key.
INSERT OR IGNORE INTO ops_config (key, value, note) SELECT 'code_merge_trusted_sources--bak-20261006T0730Z', value, 'backup before TRANSFORMATION-LOOP-1 appended qnfo-fleet-control|TP- and TRANSFORMATION-PROGRAM-1|TP-' FROM ops_config WHERE key = 'code_merge_trusted_sources';
UPDATE ops_config SET value = value || ',qnfo-fleet-control|TP-,TRANSFORMATION-PROGRAM-1|TP-', updated_at = datetime('now') WHERE key = 'code_merge_trusted_sources' AND value NOT LIKE '%qnfo-fleet-control|TP-%';

INSERT OR IGNORE INTO metric_registry (metric, layer, kind, formula, source_of_truth, baseline, target, owner, disposition_actor, refresh_cadence, warning_band, kill_band, state, refresh_class)
VALUES ('transformation_levers_landed_14d', 'system', 'leading',
  'COUNT(transformation_levers WHERE landed_at or verified_at in the last 14 days): levers of docs/TRANSFORMATION-PROGRAM.md that reached main or closed with evidence (qnfo-fleet-control TRANSFORMATION-LOOP-1, hourly)',
  'qnfo-audit.transformation_levers (GET https://qnfo-fleet-control.q08.workers.dev/transformation)',
  '0 (2026-10-06, before the loop)', '>= 2 every 14 days while any wave is open (the program moves); rising',
  'qnfo-fleet-control', 'trigger lt 1 -> METRIC-TRIGGER issue (migrations/2026-10-06-transformation-loop.sql)', 'hourly', '< 2', '< 1', 'MEASURED', 'computed');

-- First value from the seed, so the trigger below judges a number and not NULL before the loop's first tick.
UPDATE metric_registry SET last_value = (SELECT COUNT(*) FROM transformation_levers WHERE COALESCE(verified_at, landed_at) >= strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-14 days')), last_refreshed = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE metric = 'transformation_levers_landed_14d' AND last_value IS NULL;

INSERT OR IGNORE INTO analytics_metric_triggers (metric_key, title, source_table, operator, threshold, priority, action, owner, queue_target, cooldown_hours, enabled, notes)
SELECT 'transformation_levers_landed_14d', 'Autonomy gap: no transformation lever landed in 14 days (the program is not moving)', 'registry', 'lt', 1, 7,
  'Pillar autonomy (TRANSFORMATION-LOOP-1, owner directive 2026-10-06: a continuing, fully autonomous program of transformational change). No lever of docs/TRANSFORMATION-PROGRAM.md reached main or closed with evidence in 14 days. Read GET https://qnfo-fleet-control.q08.workers.dev/transformation: (1) last_run older than 2h means the hourly tick is not running (qnfo-fleet-control /health, cloud_ops_events transformation-tick-<day>); (2) levers stuck in dispatched: the code loop refused or parked them (code_tasks last_error; CODE-TASK-NEEDS-SESSION-1 rows name the ones that need a session); (3) levers stuck in session: the open TP-* session-task issues are the queue, take the oldest in wave order; (4) nothing pending in the active wave: the wave''s exit metrics name what is missing. Never raise a cap, never add a model call while a fleet_budget cap is breached, never weaken a guard to make a lever land. Definition of done: metric_registry.transformation_levers_landed_14d >= 1; record before and after in issue_triage.close_evidence.',
  'qnfo-fleet-control', 'agent_issues', 24, 1, 'TRANSFORMATION-LOOP-1 (migrations/2026-10-06-transformation-loop.sql)'
WHERE NOT EXISTS (SELECT 1 FROM analytics_metric_triggers x WHERE x.metric_key = 'transformation_levers_landed_14d');

-- Closing probe for the loop itself: a run in the last 2 hours. Pending until the first run.
INSERT INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status)
VALUES ('transformation-loop-1', NULL,
  'qnfo-fleet-control 0.4.131+ deployed; transformation_levers seeded',
  'observe only: the hourly tick writes transformation_runs and cloud_ops_events transformation-tick-<day>',
  'SELECT ''ok'' AS expected, CASE WHEN (SELECT MAX(ts) FROM transformation_runs) IS NULL THEN ''pending: loop has not run'' WHEN (SELECT MAX(ts) FROM transformation_runs) < strftime(''%Y-%m-%dT%H:%M:%SZ'',''now'',''-2 hours'') THEN ''stale: last run older than 2h'' ELSE ''ok'' END AS observed',
  'd1-query', 3, 'qnfo-fleet-control', 1, 'active')
ON CONFLICT(class) DO UPDATE SET precondition=excluded.precondition, action=excluded.action, verify_probe=excluded.verify_probe, status='active';
