-- OWNER-ONLY-SEED-1 (2026-10-01): the owner-only actions from docs/PORTFOLIO-OPERATIONS.md s5-6, docs/STRATEGY.md s10 and
-- docs/QUNIVERSE-CHARTER.md s7, seeded into the human queue read by https://fleet.qnfo.org/ (owner approved seeding).
-- Idempotent (INSERT OR IGNORE on the UNIQUE slug). Resolve a row when the owner says it is done:
--   UPDATE human_actions SET status='resolved', resolved_at=datetime('now'), updated_at=datetime('now'), resolution='<evidence>' WHERE slug='<slug>' AND status='open';
-- or POST /api/human {"op":"resolve","slug":"...","resolution":"..."} with x-loop-token. The objective-revision item is derived live (goals) and needs no row.
CREATE TABLE IF NOT EXISTS human_actions (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT UNIQUE, title TEXT NOT NULL, why TEXT, default_in_effect TEXT, action TEXT, url TEXT, sev TEXT DEFAULT 'normal', due TEXT, status TEXT DEFAULT 'open', source TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), resolved_at TEXT, resolution TEXT);
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('identity-copy-approve','Paste the approved profile copy into every profile, fix the Google Scholar attribution and GitHub bio, and say which LinkedIn URL is yours','The system may not change your name, bio, CV or public profiles (STRATEGY s5), and most of these sites cannot be edited by API.','Profiles stay as they are; launch posts wait.','Use the copy in your Identity tracker (item 8). LinkedIn cannot be edited by API.','','normal','2026-10-14','open','owner-only:identity-tracker-8');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('buffer-connect-linkedin','Connect LinkedIn in Buffer (then approve each draft with one tap)','LinkedIn''s API terms forbid automated posting, so only you can authorise the account and each draft needs your tap.','LinkedIn posting stays off; other channels are unaffected.','Connect LinkedIn in Buffer (optionally Mastodon, Threads, X).','','normal','2026-10-08','open','owner-only:PORTFOLIO-OPERATIONS-s6');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('ga4-gsc-access','Give the fleet GA4 Viewer and Search Console access','Only you can grant access to your analytics properties. Without it the scorecard has no search impressions or engaged sessions.','Those reach sources show ''not connected'' (never zeros); decisions use the signals that are readable.','GA4: add the fleet''s service account as Viewer and share the property ID. Search Console: verify qnfo.org and add the same account as Full user.','','normal','2026-10-08','open','owner-only:PORTFOLIO-OPERATIONS-s6');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('arxiv-endorsement','Ask one established arXiv author for a personal endorsement','Since 2026-01-21 a new arXiv author needs a personal endorsement. It cannot be requested for you, and never as a mass request.','The arXiv package for work 1 waits; Zenodo stays the canonical record.','Ask one established author in the field, individually.','','normal','','open','owner-only:STRATEGY-s10');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('orcid-link-works','Add the selected works to ORCID (Search & link)','ORCID auto-update is deliberately off (it would add every DOI); linking is an action on your own ORCID account.','ORCID stays as it is; the works remain on Zenodo and the site.','Use ORCID ''Search & link'' for the selected works (STRATEGY 2.4).','https://orcid.org/0009-0002-4317-5604','normal','','open','owner-only:STRATEGY-s10');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('rotate-cf-token','Rotate the identity-bound Cloudflare token (SEC-EXPOSED-CREDENTIALS-UNROTATED-1)','Exposed credentials are unrotated. Only the credential holder can rotate it: automated rotation on a 401 would turn a stale secret into an outage (policy ''Never'').','The current credential keeps serving, so the exposure continues until you rotate it.','Create the new token in Cloudflare, then set it as the secret in each Worker that holds it (Workers & Pages > the Worker > Settings > Variables and Secrets).','','normal','','open','owner-only:QUNIVERSE-CHARTER-s7');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('nlnet-restack-submit','Submit the NLnet Restack Fund application','Applications are never sent automatically (STRATEGY s5), and a grant also moves the funding leg of the review gate.','No application is sent; the draft stays in the repo and the fleet rewrites it by 2026-10-20.','Review funding/NLNET_RESTACK_2026-11.md and submit by 2026-11-02 (deadline 2026-11-03 12:00 CET).','https://github.com/QNFO/qnfo-workers/blob/main/funding/NLNET_RESTACK_2026-11.md','normal','2026-11-02','open','owner-only:PORTFOLIO-OPERATIONS-s5');
-- NO-CLAUDE-RUNTIME-DEPENDENCY-1 (applied to production 2026-10-01): the claude.ai connectors card is dismissed, the profile-copy
-- card no longer links claude.ai, and the owner's identity-tracker to-dos (short, non-sensitive titles) are queued.
UPDATE human_actions SET status='dismissed', resolved_at=datetime('now'), updated_at=datetime('now'), resolution='superseded by owner directive 2026-10-01: no runtime dependency on claude.ai; Routines to be ported to Cloudflare crons (ROUTINES-ON-CLAUDE-1)' WHERE slug='routine-connectors' AND status='open';
UPDATE human_actions SET title='Paste the approved profile copy into every profile, fix the Google Scholar attribution and GitHub bio, and say which LinkedIn URL is yours', url='', due='2026-10-14', source='owner-only:identity-tracker-8' WHERE slug='identity-copy-approve' AND status='open';
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('idtr-2-zenodo-request','Send the drafted Zenodo support request (Identity tracker item 2)','Only the record owner can ask Zenodo support to remove files from published records, and it is time-sensitive.','The files stay public until Zenodo removes them.','Send the drafted request through the Zenodo support form while logged in as the record owner.','https://zenodo.org/support','urgent','2026-10-03','open','owner-only:identity-tracker-2');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('idtr-3-patent-decision','Decide whether to file full patent applications before the windows close (last 2026-11-30), and approve the wording','Filing and legal commitments are yours; provisional windows lapse 12 months after filing.','The provisionals lapse on their dates; the public wording stays unreviewed.','Decide, then approve the wording in your Identity tracker (item 3).','','normal','2026-10-07','open','owner-only:identity-tracker-3');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('idtr-4-prior-org-status','Confirm the status of your prior nonprofit (Identity tracker item 4)','Only you can confirm it is yours and still active; leads that pay through it depend on it.','Those leads stay out of the shortlist.','Confirm it, then state it on your profiles.','','normal','2026-10-07','open','owner-only:identity-tracker-4');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('idtr-6-october-deadlines','Pick which October deadlines to pursue (15 Oct, 31 Oct)','Applications are never sent automatically (STRATEGY s5) and each commits your time.','Nothing is drafted for the ones you do not pick.','Choose from the options in your Identity tracker (item 6).','','normal','2026-10-06','open','owner-only:identity-tracker-6');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('idtr-7-fri-application','Submit the Forecasting Research Institute application (one form, answers drafted)','Applications are never sent automatically (STRATEGY s5); the form has a work test.','No application is sent.','Review the drafted answers in your Identity tracker (item 7) and submit the form.','','normal','2026-10-09','open','owner-only:identity-tracker-7');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('idtr-cv-facts','Confirm four CV facts: QNFO start year, one public email, whether PMP/AICP are still active, and your location and work-authorization line','Only you can confirm facts about yourself; the system leaves them out rather than guess.','The CV omits those facts.','Answer the four checkboxes in your Identity doc.','','normal','','open','owner-only:identity-doc');
