-- OWNER-ONLY-SEED-1 (2026-10-01): the owner-only actions from docs/PORTFOLIO-OPERATIONS.md s5-6, docs/STRATEGY.md s10 and
-- docs/QUNIVERSE-CHARTER.md s7, seeded into the human queue read by https://fleet.qnfo.org/ (owner approved seeding).
-- Idempotent (INSERT OR IGNORE on the UNIQUE slug). Resolve a row when the owner says it is done:
--   UPDATE human_actions SET status='resolved', resolved_at=datetime('now'), updated_at=datetime('now'), resolution='<evidence>' WHERE slug='<slug>' AND status='open';
-- or POST /api/human {"op":"resolve","slug":"...","resolution":"..."} with x-loop-token. The objective-revision item is derived live (goals) and needs no row.
CREATE TABLE IF NOT EXISTS human_actions (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT UNIQUE, title TEXT NOT NULL, why TEXT, default_in_effect TEXT, action TEXT, url TEXT, sev TEXT DEFAULT 'normal', due TEXT, status TEXT DEFAULT 'open', source TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), resolved_at TEXT, resolution TEXT);
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('identity-copy-approve','Approve the brand line, bios and CV, then paste the headline and bio into LinkedIn','The system may not change your name, bio, CV or public profiles (STRATEGY s5), and LinkedIn cannot be edited by API.','Launch posts wait on your approval; profiles stay as they are.','Approve or edit in the Identity doc (tracker item 1), then paste the headline and bio into LinkedIn.','https://claude.ai/code/artifact/553e4316-5725-4601-bf41-e5fd7102c96b','normal','2026-10-07','open','owner-only:PORTFOLIO-OPERATIONS-s6');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('buffer-connect-linkedin','Connect LinkedIn in Buffer (then approve each draft with one tap)','LinkedIn''s API terms forbid automated posting, so only you can authorise the account and each draft needs your tap.','LinkedIn posting stays off; other channels are unaffected.','Connect LinkedIn in Buffer (optionally Mastodon, Threads, X).','','normal','2026-10-08','open','owner-only:PORTFOLIO-OPERATIONS-s6');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('ga4-gsc-access','Give the fleet GA4 Viewer and Search Console access','Only you can grant access to your analytics properties. Without it the scorecard has no search impressions or engaged sessions.','Those reach sources show ''not connected'' (never zeros); decisions use the signals that are readable.','GA4: add the fleet''s service account as Viewer and share the property ID. Search Console: verify qnfo.org and add the same account as Full user.','','normal','2026-10-08','open','owner-only:PORTFOLIO-OPERATIONS-s6');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('routine-connectors','Add the Cloudflare Developer Platform and Claude Docs connectors to the two portfolio Routines','Routines created from a session store no connectors in this organisation; only you can add them in claude.ai.','Runs fall back to repo workflows and the dashboard API; they cannot read D1 or the Identity doc directly.','In claude.ai Routines, add both connectors to ''QNFO portfolio management'' (trig_01KNd7qpeeLwKdWAoKCmDSTt) and to ''Identity and brand weekly review''.','','normal','','open','owner-only:PORTFOLIO-OPERATIONS-s6');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('arxiv-endorsement','Ask one established arXiv author for a personal endorsement','Since 2026-01-21 a new arXiv author needs a personal endorsement. It cannot be requested for you, and never as a mass request.','The arXiv package for work 1 waits; Zenodo stays the canonical record.','Ask one established author in the field, individually.','','normal','','open','owner-only:STRATEGY-s10');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('orcid-link-works','Add the selected works to ORCID (Search & link)','ORCID auto-update is deliberately off (it would add every DOI); linking is an action on your own ORCID account.','ORCID stays as it is; the works remain on Zenodo and the site.','Use ORCID ''Search & link'' for the selected works (STRATEGY 2.4).','https://orcid.org/0009-0002-4317-5604','normal','','open','owner-only:STRATEGY-s10');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('rotate-cf-token','Rotate the identity-bound Cloudflare token (SEC-EXPOSED-CREDENTIALS-UNROTATED-1)','Exposed credentials are unrotated. A session cannot mint or rotate a live credential (policy ''Never''; #1701 shows what happens when sessions try).','The current credential keeps serving, so the exposure continues until you rotate it.','Rotate the token you hold; the fleet then re-installs it under the secret lease (CLAUDE.md, #1701).','','normal','','open','owner-only:QUNIVERSE-CHARTER-s7');
INSERT OR IGNORE INTO human_actions (slug, title, why, default_in_effect, action, url, sev, due, status, source) VALUES ('nlnet-restack-submit','Submit the NLnet Restack Fund application','Applications are never sent automatically (STRATEGY s5), and a grant also moves the funding leg of the review gate.','No application is sent; the draft stays in the repo and the fleet rewrites it by 2026-10-20.','Review funding/NLNET_RESTACK_2026-11.md and submit by 2026-11-02 (deadline 2026-11-03 12:00 CET).','https://github.com/QNFO/qnfo-workers/blob/main/funding/NLNET_RESTACK_2026-11.md','normal','2026-11-02','open','owner-only:PORTFOLIO-OPERATIONS-s5');
