-- ISSUE-PLANNER-1 (2026-10-02, pillar: autonomy). Owner directive 2026-10-02: "Filing an issue is not fixing it. Something
-- still has to do the work: the fleet's code agent for code changes it can handle." Applied live; idempotent.
--
-- qnfo-code-orchestrator 0.3.3 plans prose issues into code tasks (see its ISSUE-PLANNER-1 block). This migration:
--   1. creates issue_plans (the planner's ledger) so the metric step below never reads a missing table;
--   2. lets the merge runner (qnfo-fleet-control CODE-TASK-MERGE-RUNNER-1) merge code tasks that come from the fleet's own
--      metric-trigger issues: ops_config code_merge_trusted_sources = the built-in default plus
--      'qnfo-fleet-control|METRIC-TRIGGER-'. Their text is generated by qnfo-fleet-control from analytics_metric_triggers
--      (a table written only by migrations and sessions), not from feeds or email, so untrusted text still cannot reach
--      main. Every other gate is unchanged (scope, integrity, required checks, revertible, live check, auto-revert).
--      To undo: DELETE FROM ops_config WHERE key = 'code_merge_trusted_sources' (the runner falls back to its default).
--   3. registers two metrics on the hourly metric-refresh task and a trigger for the first:
--      autonomous_fixes_30d   code tasks from issues that the runner merged and verified live in 30 days (the number that
--                             says the fleet fixed something itself; target >= 4/30d);
--      planner_code_share_30d share of the planner's decisions in 30 days that became a code task (report).

CREATE TABLE IF NOT EXISTS issue_plans (issue_id INTEGER PRIMARY KEY, planned_at TEXT NOT NULL, outcome TEXT NOT NULL, detail TEXT, task_id TEXT, path TEXT, model TEXT, attempts INTEGER DEFAULT 1);

INSERT INTO ops_config (key, value) VALUES ('code_merge_trusted_sources', 'qnfo-fleet-dashboard:owner-request|OWNER-TASK-,qnfo-fleet-dashboard:owner-request|OWNER-NOTE-,claude-session*,claude-code-session*,qnfo-fleet-control|METRIC-TRIGGER-')
ON CONFLICT(key) DO UPDATE SET value = CASE WHEN instr(ops_config.value, 'qnfo-fleet-control|METRIC-TRIGGER-') > 0 THEN ops_config.value ELSE ops_config.value || ',qnfo-fleet-control|METRIC-TRIGGER-' END;

INSERT OR IGNORE INTO metric_registry (metric, layer, kind, formula, source_of_truth, baseline, target, owner, disposition_actor, refresh_cadence, warning_band, kill_band, state, refresh_class) VALUES
 ('autonomous_fixes_30d', 'system', 'lagging', 'count(code_tasks WHERE goal LIKE ''[issue #%'' AND merged_by = ''qnfo-fleet-control'' AND merge_state = ''deployed'' AND merged_at in the last 30 days): issues the fleet fixed in code, merged and verified live without a person', 'qnfo-audit.code_tasks', '0', '>= 4 per 30 days', 'qnfo-code-orchestrator', 'ISSUE-PLANNER-1 -> code loop -> CODE-TASK-MERGE-RUNNER-1', 'hourly', '< 1', '< 1 for 30 days', 'MEASURED', 'computed'),
 ('planner_code_share_30d', 'system', 'leading', 'issue_plans in the last 30 days with outcome queued / all outcomes except refused; n/a with none', 'qnfo-audit.issue_plans', 'n/a', 'report', 'qnfo-code-orchestrator', 'report only', 'hourly', NULL, NULL, 'MEASURED', 'computed');

UPDATE fleet_tasks SET definition = json_insert(definition, '$.steps[#]', json('{"type": "sql", "db": "AUDIT", "sql": "UPDATE metric_registry SET last_value = CASE metric WHEN ''autonomous_fixes_30d'' THEN CAST((SELECT COUNT(*) FROM code_tasks WHERE goal LIKE ''[issue #%'' AND merged_by = ''qnfo-fleet-control'' AND merge_state = ''deployed'' AND merged_at >= strftime(''%Y-%m-%dT%H:%M:%SZ'', ''now'', ''-30 days'')) AS TEXT) ELSE COALESCE(CAST((SELECT ROUND(1.0 * SUM(outcome = ''queued'') / NULLIF(SUM(outcome <> ''refused''), 0), 2) FROM issue_plans WHERE planned_at >= strftime(''%Y-%m-%dT%H:%M:%SZ'', ''now'', ''-30 days'')) AS TEXT), ''n/a'') END, last_refreshed = strftime(''%Y-%m-%dT%H:%M:%SZ'', ''now''), state = ''MEASURED'' WHERE metric IN (''autonomous_fixes_30d'', ''planner_code_share_30d'')"}')),
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = 'metric-refresh' AND instr(definition, 'autonomous_fixes_30d') = 0;

INSERT OR IGNORE INTO analytics_metric_triggers (metric_key, title, source_table, operator, threshold, priority, action, owner, queue_target, cooldown_hours, enabled, notes)
VALUES ('autonomous_fixes_30d', 'Autonomy gap: the fleet fixed nothing in code by itself in 30 days', 'registry', 'lt', 1, 8,
 'Pillar autonomy. No issue went plan -> code task -> merged -> verified live in 30 days. Read issue_plans (outcomes and reasons) and code_tasks (status, last_error, merge_note) to find the stage where work stops: not planned (no trusted issue names a worker), planned but invalid (anchor or goal), proposed but failing verify, published but not merged (merge gates), merged but reverted. Fix that stage; say which on the issue. Definition of done: autonomous_fixes_30d >= 1 in metric_registry, with the task id in issue_triage.close_evidence.',
 'qnfo-code-orchestrator', 'agent_issues', 168, 1, 'ISSUE-PLANNER-1 2026-10-02');
