-- ATTENTION-LOOP-1 (2026-10-06, pillar reach; owner directive 2026-10-06 07:44Z: "track granular impressions/eyeballs (humans,
-- not bots/crawlers/AI) from outreach channels and audit to do more of what gets noticed; if something isn't getting noticed
-- it either needs to be promoted more/better or stop doing it and shift attention to higher-impact signals; track all
-- metrics in signal and feedback loops"). qnfo-fleet-dashboard 1.24.0 writes the per-item human ledger and the daily
-- scorecard (attention_scorecard, attention_decisions, ops_config attention_channel_share); qnfo-social 0.8.0 applies the
-- shares. This file registers the loop's metrics with their triggers (METRIC-CLOSED-LOOP-1), the contract on its heartbeat,
-- and two transformation levers for the attribution gaps a session measured (no UTM read on page loads; digest links
-- untagged). Idempotent; applied by the session that wrote it. Rollback: DELETE FROM analytics_metric_triggers WHERE
-- metric_key IN ('attention_events_7d','pages_noticed_7d','attention_channels_stopped','attention_decision_efficacy_30d');
-- DELETE FROM metric_registry WHERE metric IN ('attention_events_7d','attention_per_post_7d','pages_noticed_7d',
-- 'attention_channels_stopped','attention_decision_efficacy_30d'); DELETE FROM remediation_contracts WHERE class =
-- 'attention-loop-1'; DELETE FROM transformation_levers WHERE tp = 7 AND n IN (9, 10); DROP TABLE attention_scorecard;
-- DROP TABLE attention_decisions; DELETE FROM ops_config WHERE key = 'attention_channel_share'.

CREATE TABLE IF NOT EXISTS attention_scorecard (day TEXT NOT NULL, window_days INTEGER NOT NULL, channel TEXT NOT NULL, items INTEGER, attention REAL, per_item REAL, visits REAL, impressions REAL, verdict TEXT, share REAL, reason TEXT, retest_at TEXT, extra TEXT, created_at TEXT, PRIMARY KEY (day, window_days, channel));
CREATE TABLE IF NOT EXISTS attention_decisions (id INTEGER PRIMARY KEY AUTOINCREMENT, day TEXT NOT NULL, channel TEXT NOT NULL, from_verdict TEXT, to_verdict TEXT, from_share REAL, to_share REAL, reason TEXT, evidence TEXT, prediction TEXT, verify_at TEXT, outcome TEXT, outcome_detail TEXT, verified_at TEXT, created_at TEXT);

INSERT OR IGNORE INTO metric_registry (metric, layer, kind, formula, source_of_truth, baseline, target, owner, disposition_actor, refresh_cadence, warning_band, kill_band, state, refresh_class) VALUES
 ('attention_events_7d', 'fleet', 'leading', 'Human attention events in the last 7 complete UTC days across every outreach channel: social engagements (likes, reposts, quotes, replies from others, reactions, comments, shares, clicks) on the week''s posts + bot-filtered page loads referred by a social host + replies to the week''s outreach sends + bot-filtered page loads of public pages referred from outside the fleet (qnfo-fleet-dashboard ATTENTION-LOOP-1, daily after the reach ingest)', 'qnfo-audit.attention_scorecard (window 7) and reach_signals sources cf-rum-human, bluesky, buffer; GET https://fleet.qnfo.org/api/attention', 'measured on first run after 2026-10-06 (the 14-day read: 10 Bluesky likes, 15 LinkedIn-referred loads, 30 external loads)', 'rising; >= 100 a week by 2026-12-31 (STRATEGY s6.3)', 'qnfo-social', 'trigger lt 10 -> METRIC-TRIGGER issue (migrations/2026-10-06-attention-loop.sql)', 'daily', '< 20', '< 10', 'MEASURED', 'computed'),
 ('attention_per_post_7d', 'fleet', 'leading', 'Social engagements per post over the last 7 complete UTC days, all social channels together (the scorecard''s per-channel figures are in attention_scorecard); n/a when no post was sent (qnfo-fleet-dashboard ATTENTION-LOOP-1)', 'qnfo-audit.attention_scorecard window 7, channels bluesky, linkedin, mastodon, x', 'Bluesky read 0.1 on 2026-10-06 (10 likes on 100 posts)', '>= 1 engagement per post (the PROMOTE line) by 2026-12-31', 'qnfo-social', 'the per-channel verdicts (ops_config attention_channel_share) move the shares; no trigger: attention_events_7d and the stopped count carry the breach', 'daily', '< 0.5', '< 0.1', 'MEASURED', 'computed'),
 ('pages_noticed_7d', 'fleet', 'leading', 'Public pages and papers with at least one bot-filtered page load referred from outside the fleet''s domains in the last 7 complete UTC days (reach_signals source cf-rum-human, metric external_pageviews; qnfo-fleet-dashboard ATTENTION-LOOP-1)', 'qnfo-audit.reach_signals cf-rum-human external_pageviews; attention_scorecard channel web', 'n/a until the first ingest after 1.24.0 (the 7-day site total was 30 external loads on 2026-10-06)', 'rising; >= 20 distinct items a week by 2026-12-31', 'qnfo-gateway', 'trigger lt 5 -> METRIC-TRIGGER issue (migrations/2026-10-06-attention-loop.sql)', 'daily', '< 10', '< 5', 'MEASURED', 'computed'),
 ('attention_channels_stopped', 'fleet', 'guard', 'Social channels whose latest attention verdict is STOP (share 0): the loop shifting effort away from channels that drew no human attention over 28 days; guard: more than one stopped channel at once means the content, not the channel, is the problem (qnfo-fleet-dashboard ATTENTION-LOOP-1)', 'qnfo-audit.attention_scorecard (window 28, verdict STOP); ops_config attention_channel_share', '0 before the loop', '<= 1 at any time; a stopped channel is re-tested after 28 days', 'qnfo-social', 'trigger gt 1 -> METRIC-TRIGGER issue: promote better (content, format, timing) before stopping more (migrations/2026-10-06-attention-loop.sql)', 'daily', '> 1', '> 2', 'MEASURED', 'computed'),
 ('attention_decision_efficacy_30d', 'fleet', 'lagging', 'Share of attention decisions verified in the last 30 days whose channel''s attention per item rose by 20%+ in the 7 days after the decision (improved / judged, INSUFFICIENT excluded); n/a until a decision is 7 days old (qnfo-fleet-dashboard ATTENTION-LOOP-1)', 'qnfo-audit.attention_decisions (outcome improved | flat | worse)', 'n/a until 2026-10-14', '>= 0.5 (a rule that moves attention less than half the time is replaced, METRIC-CLOSED-LOOP-1)', 'qnfo-fleet-dashboard', 'trigger lt 0.34 -> METRIC-TRIGGER issue (migrations/2026-10-06-attention-loop.sql)', 'daily', '< 0.5', '< 0.34', 'MEASURED', 'computed');

-- Until the first scorecard runs the values are unreadable (n/a), never 0, so no trigger fires on an empty ledger.
UPDATE metric_registry SET last_value = 'n/a: first scorecard after qnfo-fleet-dashboard 1.24.0 deploys', last_refreshed = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE metric IN ('attention_events_7d', 'attention_per_post_7d', 'pages_noticed_7d', 'attention_channels_stopped', 'attention_decision_efficacy_30d') AND last_value IS NULL;

INSERT OR IGNORE INTO analytics_metric_triggers (metric_key, title, source_table, operator, threshold, priority, action, owner, queue_target, cooldown_hours, enabled, notes)
SELECT 'attention_events_7d', 'Reach gap: under 10 human attention events in a week across every outreach channel', 'registry', 'lt', 10, 6,
  'Pillar reach (ATTENTION-LOOP-1, owner directive 2026-10-06). The week drew under 10 human attention events in total (engagements, referred visits, replies, external page loads). Read GET https://fleet.qnfo.org/api/attention: the per-channel rows say which channel sent items and drew nothing. Levers, in order: (1) items were sent but drew nothing: the verdicts already cut those channels'' shares; move the week''s posts to the items the web rows show as noticed (top_external) and the formats the learner''s posterior favours (GET https://qnfo-social.q08.workers.dev/learner); (2) no items were sent: the drains are held (qnfo-social run ledger social-channels-<day>, social-drain-<day>) or every share is 0; (3) the ledger is empty: reach-ingest-<day> and attention-scorecard-<day> rows name the skipped source. Never raise a cap (STRATEGY s4), never add a model call while a fleet_budget cap is breached. Definition of done: attention_events_7d >= 10 on two consecutive days; record before and after in issue_triage.close_evidence.',
  'qnfo-social', 'agent_issues', 72, 1, 'ATTENTION-LOOP-1 (migrations/2026-10-06-attention-loop.sql)'
WHERE NOT EXISTS (SELECT 1 FROM analytics_metric_triggers x WHERE x.metric_key = 'attention_events_7d');
INSERT OR IGNORE INTO analytics_metric_triggers (metric_key, title, source_table, operator, threshold, priority, action, owner, queue_target, cooldown_hours, enabled, notes)
SELECT 'pages_noticed_7d', 'Reach gap: fewer than 5 public pages were found from outside the fleet in a week', 'registry', 'lt', 5, 6,
  'Pillar reach (ATTENTION-LOOP-1). Under 5 distinct public pages or papers drew a bot-filtered load referred from outside the fleet in 7 days (reach_signals cf-rum-human external_pageviews). Levers: (1) the items that were noticed (GET https://fleet.qnfo.org/api/attention, web.top_external) are the ones to promote: the channel drain already orders by attention; (2) the pages with human loads but no external referrer are reached only by direct links: the subscribe box and the selected-works links on qnfo.org (REACH-IDEA-1 ideas) and the Scholar PDF coverage (transformation lever T7.2) are the organic levers; (3) a week with no row at all is an ingest fault (reach-ingest-<day>). Definition of done: pages_noticed_7d >= 5 on two consecutive days; record before and after in issue_triage.close_evidence.',
  'qnfo-gateway', 'agent_issues', 72, 1, 'ATTENTION-LOOP-1 (migrations/2026-10-06-attention-loop.sql)'
WHERE NOT EXISTS (SELECT 1 FROM analytics_metric_triggers x WHERE x.metric_key = 'pages_noticed_7d');
INSERT OR IGNORE INTO analytics_metric_triggers (metric_key, title, source_table, operator, threshold, priority, action, owner, queue_target, cooldown_hours, enabled, notes)
SELECT 'attention_channels_stopped', 'Guard: more than one social channel stopped by the attention loop at once', 'registry', 'gt', 1, 5,
  'Pillar reach (ATTENTION-LOOP-1, guard). Two or more social channels read STOP (share 0) at once: the evidence says the content, format or timing draws no human attention anywhere, so promoting better comes before stopping more. Read the attention_decisions rows for each stop (evidence and prediction), the learner''s posterior (GET https://qnfo-social.q08.workers.dev/learner) and the noticed items (GET https://fleet.qnfo.org/api/attention). Levers: a different format or hook on the noticed items, the re-test (28 days, automatic), or ops_config attention_thresholds (JSON: min_items, stop_items, stop_per_item, improve_per_item, promote_per_item) with the reason recorded on this issue; never raise an owner cap. Definition of done: attention_channels_stopped <= 1; record before and after in issue_triage.close_evidence.',
  'qnfo-social', 'agent_issues', 168, 1, 'ATTENTION-LOOP-1 guard (migrations/2026-10-06-attention-loop.sql)'
WHERE NOT EXISTS (SELECT 1 FROM analytics_metric_triggers x WHERE x.metric_key = 'attention_channels_stopped');
INSERT OR IGNORE INTO analytics_metric_triggers (metric_key, title, source_table, operator, threshold, priority, action, owner, queue_target, cooldown_hours, enabled, notes)
SELECT 'attention_decision_efficacy_30d', 'Loop gap: attention decisions move attention per item less than a third of the time', 'registry', 'lt', 0.34, 6,
  'Pillar reach (ATTENTION-LOOP-1). Of the attention decisions verified in 30 days, under a third raised the channel''s attention per item within 7 days (attention_decisions.outcome). METRIC-CLOSED-LOOP-1: the rule is replaced, not repeated. Read the decisions (GET https://fleet.qnfo.org/api/attention): a run of ''worse'' after PROMOTE means more items dilute attention (lower promote_per_item or the per-channel cap share); a run of ''flat'' after IMPROVE means ordering alone does not help (the learner''s format and slot arms, a different hook); edit ops_config attention_thresholds or the verdict rules in qnfo-fleet-dashboard atVerdict with the reasoning on this issue. Definition of done: attention_decision_efficacy_30d >= 0.5; record before and after in issue_triage.close_evidence.
code-task: repo=qnfo-workers path=qnfo-fleet-dashboard/worker.js
code-anchor: function atVerdict(stats, prev, th, nowIso) {',
  'qnfo-fleet-dashboard', 'agent_issues', 168, 1, 'ATTENTION-LOOP-1 (migrations/2026-10-06-attention-loop.sql)'
WHERE NOT EXISTS (SELECT 1 FROM analytics_metric_triggers x WHERE x.metric_key = 'attention_decision_efficacy_30d');

-- The loop's own heartbeat: a scorecard row every day (ok within 36 hours).
INSERT INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status)
VALUES ('attention-loop-1', NULL,
  'qnfo-fleet-dashboard 1.24.0+ deployed; reach ingest running',
  'observe only: attentionScorecard runs after each day''s reach ingest and writes cloud_ops_events attention-scorecard-<day>',
  'SELECT ''ok'' AS expected, CASE WHEN (SELECT MAX(ts) FROM cloud_ops_events WHERE id >= ''attention-scorecard-'' AND id < ''attention-scorecard.'') IS NULL THEN ''pending: no scorecard yet'' WHEN (SELECT MAX(ts) FROM cloud_ops_events WHERE id >= ''attention-scorecard-'' AND id < ''attention-scorecard.'') < strftime(''%Y-%m-%dT%H:%M:%SZ'',''now'',''-36 hours'') THEN ''stale: last scorecard older than 36h'' ELSE ''ok'' END AS observed',
  'd1-query', 3, 'qnfo-fleet-dashboard', 24, 'active')
ON CONFLICT(class) DO UPDATE SET precondition=excluded.precondition, action=excluded.action, verify_probe=excluded.verify_probe, status='active';

-- Two attribution gaps the audit measured, as transformation levers T7.9 and T7.10 (T7.6-T7.8 were taken by the Ask and
-- paper-page levers another session filed the same morning; TRANSFORMATION-LOOP-1 dispatches T7.9 to the code loop once
-- the gateway file's work claim lapses; T7.10 is a one-line change in qnfo-subscribers).
INSERT OR IGNORE INTO transformation_levers (tp, n, key, title, kind, wave, pillar, path, anchor, detail, dod, issue_id, status, note, dispatched_at, landed_at) VALUES
 (7, 9, 'utm-click-ledger', 'The public pages record bot-filtered loads that carry utm_source/utm_campaign, so a post or digest joins to the visits it caused', 'code', 'W1', 'reach', 'qnfo-gateway/worker.js', 'return withFleetCtl(await withReachLayer(await gateway_worker_default.serve(request, env, ctx), request));', 'Every social link already carries utm_source=<channel>&utm_medium=social&utm_campaign=<slug> (qnfo-social POST-ID-UTM-1), but RUM carries no query string and nothing reads the tags on a page load, so social_learner_posts.visits and the per-post visit figure stay null. In the gateway fetch handler, before serving a GET whose URL has utm_source: ctx.waitUntil of one INSERT into a utm_clicks table (day, host, path, utm_source, utm_medium, utm_campaign, ua_class, country, n) in the gateway''s DB binding (qnfo-graph, which qnfo-fleet-dashboard binds as GRAPH), ua_class bot when the user agent matches bot|crawler|spider|preview|facebookexternalhit|slackbot|twitterbot|linkedinbot|mastodon|bluesky|cardyb|headless, else human; no cookie, no IP, no per-recipient id. The dashboard reach ingest then reads GRAPH.utm_clicks into reach_signals source utm (channel = utm_source, entity campaign = utm_campaign, metric clicks_human / clicks_bot).', 'reach_signals carries source utm rows for the previous day and social_learner_posts.visits is non-null for a post older than 72h', NULL, 'pending', 'filed by ATTENTION-LOOP-1 (migrations/2026-10-06-attention-loop.sql, PR 678); the gateway file carried a work claim until 09:47Z on 2026-10-06 (CODE-DISPATCH-DEDUPE-1 defers the task until it lapses)', NULL, NULL),
 (7, 10, 'digest-links-utm', 'Subscriber digest links carry utm_source=digest&utm_medium=email&utm_campaign=<slug>, so a digest joins to the reads it caused', 'code', 'W1', 'reach', 'qnfo-subscribers/worker.js', NULL, 'The weekly digest builds paper links with no tag (qnfo-subscribers runDigest); with T7.9 a tagged link becomes a measured read. No per-recipient id: the campaign is the slug, the source is digest.', 'the digest HTML carries utm_source=digest on every paper link', NULL, 'pending', 'filed by ATTENTION-LOOP-1 (PR 678); add the anchor (the digest link expression in runDigest) once read from main to hand it to the code loop', NULL, NULL);
