-- 2026-10-05 code loop and merge lane (session_01KzS1yjXATqG3KDBSEyNTAs/B1; agent_issues 1834, 1876, 1877, 1928, 1960, 1965, 1975, 1800).
-- Pillar: autonomy. Applied live to qnfo-audit on 2026-10-05 ~16:15Z through the D1 API; this file is the record and is idempotent.
-- Backup taken first: infra_state id 'backup-metric-refresh-20261005-b1-superseded-share' holds the previous
-- fleet_tasks 'metric-refresh' definition and the actions of triggers 378 and 537.
-- Rollback: restore fleet_tasks.definition from that backup row; DELETE FROM metric_registry WHERE metric = 'code_task_superseded_share_30d';
-- strip the text from 'ACT-BRIDGE-1 lever (B1 2026-10-05' to the end of analytics_metric_triggers.action for id 537.
--
-- 1. code_task_superseded_share_30d: the diagnostic split of code_task_success_rate_30d (#1877). Of 54 code tasks finished in
--    30 days, 16 merged and 22 ended closed because another change to the same file got there first. The success formula is
--    unchanged (never lower the bar); this shows the real failures next to it. Trigger exemption: trigger #378 already files the
--    outcome and CODE-DISPATCH-DEDUPE-1 (qnfo-code-orchestrator 0.3.16) is the lever, so a second trigger would file it twice.
INSERT OR IGNORE INTO metric_registry (metric, layer, kind, formula, source_of_truth, baseline, target, owner, disposition_actor, refresh_cadence, warning_band, kill_band, last_value, last_refreshed, state, refresh_class) VALUES ('code_task_superseded_share_30d', 'operational', 'leading', 'share of code tasks finished in 30d (status merged, needs_human, closed, failed; created in the last 30d; n/a under 3) that ended closed because another change to the same file got there first: merge_state superseded, or merge_note/last_error says superseded, stale base, conflicts with main or already shipped. The diagnostic split of code_task_success_rate_30d (CODE-CLOSE-TRANSIENT-1, agent_issues 1877): real failures = finished - merged - superseded. Trigger exemption: trigger #378 (code_task_success_rate_30d) already files the outcome and CODE-DISPATCH-DEDUPE-1 (qnfo-code-orchestrator 0.3.16) is the lever, so a second trigger would file the same breach twice', 'qnfo-audit.code_tasks', '0.41 (22 of 54, 2026-10-05)', '<= 0.10', 'qnfo-code-orchestrator', 'trigger #378 code_task_success_rate_30d -> agent_issues (owner qnfo-code-orchestrator)', 'hourly', '> 0.25', '> 0.40', NULL, NULL, 'MEASURED', 'computed');
-- refreshed hourly by the existing fleet_tasks 'metric-refresh' step 4 (no new cron):
UPDATE fleet_tasks SET definition = json_set(definition, '$.steps[4].sql', replace(replace(json_extract(definition, '$.steps[4].sql'), 'WHEN ''breach_code_task_pct'' THEN', 'WHEN ''code_task_superseded_share_30d'' THEN (SELECT CASE WHEN COUNT(*) >= 3 THEN CAST(ROUND(1.0 * SUM(CASE WHEN status = ''closed'' AND (merge_state = ''superseded'' OR lower(COALESCE(merge_note, '''') || '' '' || COALESCE(last_error, '''')) LIKE ''%supersed%'' OR lower(COALESCE(merge_note, '''') || '' '' || COALESCE(last_error, '''')) LIKE ''%stale base%'' OR lower(COALESCE(merge_note, '''') || '' '' || COALESCE(last_error, '''')) LIKE ''%conflicts with main%'' OR lower(COALESCE(merge_note, '''') || '' '' || COALESCE(last_error, '''')) LIKE ''%already shipped%'') THEN 1 ELSE 0 END) / COUNT(*), 2) AS TEXT) ELSE ''n/a: under 3 finished code tasks in 30d'' END FROM code_tasks WHERE status IN (''merged'', ''needs_human'', ''closed'', ''failed'') AND created_at >= strftime(''%Y-%m-%dT%H:%M:%fZ'', ''now'', ''-30 days'')) WHEN ''breach_code_task_pct'' THEN'), 'WHERE metric IN (''code_tasks_30d'', ''code_task_success_rate_30d'', ''breach_code_task_pct'')', 'WHERE metric IN (''code_tasks_30d'', ''code_task_success_rate_30d'', ''breach_code_task_pct'', ''code_task_superseded_share_30d'')')), updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = 'metric-refresh' AND json_extract(definition, '$.steps[4].sql') LIKE '%breach_code_task_pct%' AND instr(definition, 'code_task_superseded_share_30d') = 0;

-- 2. Trigger #378 hint pointed at statuses failures never end in (#1877).
UPDATE analytics_metric_triggers SET action = replace(action, 'Read code_tasks WHERE status IN (''needs_human'', ''failed'') (last_error, model, attempts) for the last 30 days and fix the commonest cause in qnfo-code-orchestrator', 'Read code_tasks WHERE status IN (''closed'', ''needs_human'', ''failed'', ''publish_failed'') (last_error, merge_note, merge_state, model, attempts) for the last 30 days (most failures end status closed, with the reason in merge_note or last_error; metric code_task_superseded_share_30d gives the share lost to a parallel change of the same file) and fix the commonest cause in qnfo-code-orchestrator or the merge runner') WHERE id = 378 AND instr(action, 'IN (''needs_human'', ''failed'')') > 0;

-- 3. ACT-BRIDGE-1 (#1800): the one breaching trigger whose lever is a one-file change. Anchor occurs once in
--    q08-signal-engine/worker.js at 34f14454.
UPDATE analytics_metric_triggers SET action = action || char(10) || 'ACT-BRIDGE-1 lever (B1 2026-10-05, measured in q08-signal engine_runs over 7 days: "no H1 title" is the most frequent gate_failed cause, 12 of 23, and the rejected drafts are not stored, so the cause inside normalizeDraft cannot yet be located): in gate() in q08-signal-engine/worker.js, make the "no H1 title" problem string carry the draft''s first non-empty line, at most 80 characters (for example "no H1 title (first line: ...)"), so engine_runs.error shows what the writer put where the title belongs. Diagnostic only: gate() still fails the draft; the FACTS rule and the fabrication checks are untouched. Then fix the shape it reveals in normalizeDraft.' || char(10) || 'code-task: repo=qnfo-workers path=q08-signal-engine/worker.js' || char(10) || 'code-anchor: if (!title) problems.push("no H1 title");' WHERE id = 537 AND instr(action, 'code-task:') = 0;

-- 4. #1928: ct_02oohvsbf1gbji was declared revert-failed on a cron-only worker (http null false negative); it ran and was
--    superseded by a healthy later deploy (2.3.14). Recorded as verified with the reading (see code_tasks.merge_note).
UPDATE code_tasks SET merge_state = 'verified' WHERE id = 'ct_02oohvsbf1gbji' AND merge_state = 'revert-failed';

-- 5. Closing probes (hourly remediation tick) for the code fixes, active until the canonical deploy proves them.
INSERT INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status) VALUES ('issue-1876', 1876, 'CODE-DISPATCH-DEDUPE-1 fix committed (qnfo-code-orchestrator 0.3.16, session_01KzS1yjXATqG3KDBSEyNTAs/B1); not yet merged/deployed', 'qnfo-code-orchestrator 0.3.16 refuses a code task while the same repo file has an unfinished task or a live work_claims claim; the planner defers such issues before its model call', 'SELECT ''ok'' AS expected, CASE WHEN d.ts IS NULL THEN ''pending: 0.3.16 not deployed'' WHEN (SELECT COUNT(*) FROM (SELECT repo, replace(path, ''deployed-current.worker.js'', ''worker.js'') AS f FROM code_tasks WHERE status NOT IN (''merged'',''closed'',''publish_failed'',''needs_human'',''failed'',''reverted'') GROUP BY repo, f HAVING COUNT(*) > 1)) > 0 THEN ''two unfinished code tasks share a file'' WHEN (SELECT COUNT(*) FROM code_tasks WHERE replace(substr(created_at,1,19),''T'','' '') >= d.ts AND status = ''closed'' AND (merge_state = ''superseded'' OR lower(COALESCE(merge_note,'''') || '' '' || COALESCE(last_error,'''')) LIKE ''%supersed%'' OR lower(COALESCE(merge_note,'''') || '' '' || COALESCE(last_error,'''')) LIKE ''%stale base%'')) > 0 THEN ''a task created after the deploy ended superseded'' WHEN julianday(''now'') - julianday(d.ts) < 7 THEN ''pending: under 7 days since the deploy'' ELSE ''ok'' END AS observed FROM (SELECT (SELECT MIN(replace(substr(ts,1,19),''T'','' '')) FROM fleet_deploys WHERE worker = ''qnfo-code-orchestrator'' AND ok = 1 AND (to_sha GLOB ''0.3.1[6-9]-*'' OR to_sha GLOB ''0.3.[2-9][0-9]-*'' OR to_sha GLOB ''0.[4-9].*'' OR to_sha GLOB ''[1-9].*'')) AS ts) d', 'd1-query', 3, 'qnfo-code-orchestrator', 1, 'active') ON CONFLICT(class) DO UPDATE SET precondition = excluded.precondition, action = excluded.action, verify_probe = excluded.verify_probe, verify_transport = 'd1-query', escalate_to = excluded.escalate_to, status = 'active';

INSERT INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status) VALUES ('issue-1877', 1877, 'CODE-CLOSE-REASON-1 / NOCHECKS-CONFLICT-1 fix committed (qnfo-fleet-control 0.4.117-merge-lane); code_task_superseded_share_30d registered and refreshed hourly by fleet_tasks metric-refresh (live 2026-10-05: 0.41)', 'every code-task closure records its reason; a conflicted PR with no checks is re-proposed at once; the superseded share is reported next to the success rate', 'SELECT ''ok'' AS expected, CASE WHEN d.ts IS NULL THEN ''pending: 0.4.117 merge lane not running'' WHEN (SELECT last_value FROM metric_registry WHERE metric = ''code_task_superseded_share_30d'' AND last_refreshed >= strftime(''%Y-%m-%dT%H:%M:%SZ'',''now'',''-3 hours'')) IS NULL THEN ''superseded share not measured in 3h'' WHEN (SELECT COUNT(*) FROM code_tasks WHERE status = ''closed'' AND replace(substr(updated_at,1,19),''T'','' '') >= d.ts AND trim(COALESCE(merge_note,'''')) = '''' AND trim(COALESCE(last_error,'''')) = '''') > 0 THEN ''a closure after the deploy has no reason'' WHEN (SELECT COUNT(*) FROM code_tasks WHERE status IN (''published'',''pr_open'') AND merge_note LIKE ''%computing mergeability%'' AND julianday(''now'') - julianday(replace(substr(updated_at,1,19),''T'','' '')) > 0.25) > 0 THEN ''a task waits over 6h on mergeability'' WHEN julianday(''now'') - julianday(d.ts) < 3 THEN ''pending: under 3 days since the deploy'' ELSE ''ok'' END AS observed FROM (SELECT (SELECT MIN(replace(substr(ts,1,19),''T'','' '')) FROM cloud_ops_events WHERE id >= ''branch-hygiene-tick-'' AND id < ''branch-hygiene-tick.'' AND text LIKE ''%merged_prs%'') AS ts) d', 'd1-query', 3, 'qnfo-fleet-control', 1, 'active') ON CONFLICT(class) DO UPDATE SET precondition = excluded.precondition, action = excluded.action, verify_probe = excluded.verify_probe, verify_transport = 'd1-query', escalate_to = excluded.escalate_to, status = 'active';

INSERT INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status) VALUES ('issue-1975', 1975, 'MERGE-RUNNER-REFUSAL-TAXONOMY-1 fix committed (qnfo-fleet-control 0.4.117-merge-lane): refusals end ''failed'' and go to the fleet; needs_human on 2026-10-05 16:20Z: 1 (ct_mn7hze92j88ypu, issue 1904, held by C1)', 'no merge-runner refusal parks a code task as needs_human; the only needs_human rows left would be owner-gated (none are by construction)', 'SELECT ''ok'' AS expected, CASE WHEN d.ts IS NULL THEN ''pending: 0.4.117 merge lane not running'' WHEN (SELECT COUNT(*) FROM code_tasks WHERE status = ''needs_human'') > 0 THEN ''needs_human rows: '' || (SELECT COUNT(*) FROM code_tasks WHERE status = ''needs_human'') ELSE ''ok'' END AS observed FROM (SELECT (SELECT MIN(replace(substr(ts,1,19),''T'','' '')) FROM cloud_ops_events WHERE id >= ''branch-hygiene-tick-'' AND id < ''branch-hygiene-tick.'' AND text LIKE ''%merged_prs%'') AS ts) d', 'd1-query', 3, 'qnfo-fleet-control', 1, 'active') ON CONFLICT(class) DO UPDATE SET precondition = excluded.precondition, action = excluded.action, verify_probe = excluded.verify_probe, verify_transport = 'd1-query', escalate_to = excluded.escalate_to, status = 'active';

INSERT INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status) VALUES ('issue-1965', 1965, 'STALE-PR-MERGE-FIRST-1 fix committed (qnfo-fleet-control 0.4.117-merge-lane); PR 586 (CLEF-CANDIDATE-1) closed green 2026-10-05 09:00Z, tip at refs/archive/clef-candidate-1; clef_candidate_calls_7d last_value null', 'the branch sweeper merges a quiet, green, clean session PR before CYCLE-TIME-1 would close it; every close records why it was not merged', 'SELECT ''ok'' AS expected, CASE WHEN d.ts IS NULL THEN ''pending: 0.4.117 merge lane not running'' WHEN julianday(''now'') - julianday(d.ts) < 1 THEN ''pending: under 24h of the merge lane'' WHEN (SELECT COUNT(*) FROM branch_hygiene_log WHERE action = ''close-stale-pr'' AND ok = 1 AND dry = 0 AND replace(substr(ts,1,19),''T'','' '') >= d.ts AND COALESCE(why,'''') NOT LIKE ''%not merged:%'') > 0 THEN ''a stale PR was closed without a merge attempt'' WHEN (SELECT last_value FROM metric_registry WHERE metric = ''clef_candidate_calls_7d'') IS NULL THEN ''clef_candidate_calls_7d still null (CLEF-CANDIDATE-1 not on main)'' ELSE ''ok'' END AS observed FROM (SELECT (SELECT MIN(replace(substr(ts,1,19),''T'','' '')) FROM cloud_ops_events WHERE id >= ''branch-hygiene-tick-'' AND id < ''branch-hygiene-tick.'' AND text LIKE ''%merged_prs%'') AS ts) d', 'd1-query', 3, 'qnfo-fleet-control', 1, 'active') ON CONFLICT(class) DO UPDATE SET precondition = excluded.precondition, action = excluded.action, verify_probe = excluded.verify_probe, verify_transport = 'd1-query', escalate_to = excluded.escalate_to, status = 'active';

INSERT INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status) VALUES ('issue-1960', 1960, 'merge lane + refusal taxonomy + RETIRED-TARGET-1 committed (qnfo-fleet-control 0.4.117-merge-lane, qnfo-code-orchestrator 0.3.16); 2026-10-05 16:20Z stuck rows: 2 publish_failed (ct_6dpoljohrddtgn, ct_826d5o9zjt6eix), 1 needs_human', 'no code task sits needs_human, published or publish_failed over 6h; no revert_failed in 7 days; 7 days of the merge lane', 'SELECT ''ok'' AS expected, CASE WHEN d.ts IS NULL THEN ''pending: 0.4.117 merge lane not running'' WHEN (SELECT COUNT(*) FROM code_tasks WHERE status IN (''needs_human'',''published'',''publish_failed'') AND julianday(''now'') - julianday(replace(substr(updated_at,1,19),''T'','' '')) > 0.25) > 0 THEN ''stuck code tasks: '' || (SELECT COUNT(*) FROM code_tasks WHERE status IN (''needs_human'',''published'',''publish_failed'') AND julianday(''now'') - julianday(replace(substr(updated_at,1,19),''T'','' '')) > 0.25) WHEN (SELECT COUNT(*) FROM code_tasks WHERE merge_state = ''revert-failed'' AND julianday(''now'') - julianday(replace(substr(updated_at,1,19),''T'','' '')) < 7) > 0 THEN ''revert_failed in 7 days'' WHEN julianday(''now'') - julianday(d.ts) < 7 THEN ''pending: under 7 days of the merge lane'' ELSE ''ok'' END AS observed FROM (SELECT (SELECT MIN(replace(substr(ts,1,19),''T'','' '')) FROM cloud_ops_events WHERE id >= ''branch-hygiene-tick-'' AND id < ''branch-hygiene-tick.'' AND text LIKE ''%merged_prs%'') AS ts) d', 'd1-query', 3, 'qnfo-fleet-control', 1, 'active') ON CONFLICT(class) DO UPDATE SET precondition = excluded.precondition, action = excluded.action, verify_probe = excluded.verify_probe, verify_transport = 'd1-query', escalate_to = excluded.escalate_to, status = 'active';
