-- REACH-FAILURE-MODES-1 (2026-10-09, pillar autonomy; serves reach). Owner directive 2026-10-09: schedule regular audits and
-- remediate so operation is continuous, automatic and autonomous. The failure-mode register (2026-10-08-13) had no entry for
-- the failures measured on 2026-10-05..09, so a recurrence would have waited for a session. Each entry below gets a
-- remediation_contracts detector (class fm-<key>, module failure-mode) that qnfo-fleet-control's hourly tick evaluates and
-- that files and self-closes its issue on a miss:
--   companion-publish-stall   reading.q08.org published nothing for 78h (DeepSeek 402, then a fallback length gate no draft passed).
--   host-census-stale         public_hosts_broken is only as good as its last census run (scripts/host_census.py, every 6h).
--   social-channel-drain-silent the LinkedIn/Mastodon/X drain (qnfo-social channels, every 2h at :30) stopped logging.
--   autoaudit-stale           worker_live_audit (fleet-autoaudit) is the fleet's only live-vs-repo reading; a frozen table hid drift in September.
-- Probes were run against live data on 2026-10-09 and all read pass; none is a probe that passes while the defect exists.
-- Not registered on purpose: DeepSeek unfunded (a known, degraded state the Workers AI fallback covers; a probe would pass or fail without telling anything).
-- Idempotent (INSERT OR IGNORE).
-- APPLY-BY: ci
-- DB: qnfo-audit
-- Rollback: DELETE FROM remediation_contracts WHERE class IN ('fm-companion-publish-stall','fm-host-census-stale','fm-social-channel-drain-silent','fm-autoaudit-stale'); DELETE FROM failure_modes WHERE fm_key IN ('companion-publish-stall','host-census-stale','social-channel-drain-silent','autoaudit-stale');
INSERT OR IGNORE INTO failure_modes (fm_key, failure_mode, root_cause, remediation, detector, probe_class, first_seen, issue_id, trigger_condition, symptom, blast_radius) VALUES
 ('companion-publish-stall', 'reading.q08.org published nothing for 78h', 'DeepSeek balance empty (402), then every Workers AI draft (1100-1750 words) failed the 1700-2000 word floor', 'personal-companion 1.13.0 fallback, 1.13.1 tuning, 1.13.2 fallback floor at 70%; in-worker stall detector (12h)', 'metric companion_hours_since_last_piece < 36', 'fm-companion-publish-stall', '2026-10-05', 2126, 'the paid model fails or no draft passes the gates', 'no companion_pieces row; reading.q08.org shows nothing new', 'the owner-facing reading site and its subscribers'),
 ('host-census-stale', 'the public-host census stopped running, so broken hosts go unseen', 'the census runs on the GitHub runner inside remediation_consumer.py; a stalled runner stops it silently', 'qnfo-cloud-ops dispatches the consumer after 60 idle minutes (PROBE-CADENCE-1)', 'a host-census event within 12h', 'fm-host-census-stale', '2026-10-07', NULL, 'the consumer workflow stops or its token fails', 'no cloud_ops_events kind host-census for 12h', 'every domain, route and parked-host check'),
 ('social-channel-drain-silent', 'the channel drain stops posting papers to LinkedIn, Mastodon and X without an error', 'qnfo-social crons or the Buffer token fail; the drain logs a social-run channels event every 2h even when it holds', 'qnfo-social cron; PROMOTE-ROUTE-1 (0.9.0)', 'a social-run event starting qnfo-social channels ok within 5h', 'fm-social-channel-drain-silent', '2026-10-07', 2107, 'the qnfo-social cron or Buffer API fails', 'no channels event for 5h', 'all paper promotion outside Bluesky'),
 ('autoaudit-stale', 'worker_live_audit freezes, so live-vs-repo drift goes unseen', 'the audit had no writer on an event that fires (schedule never fires on this repo)', 'fleet-autodeploy chained off push and workflow_run', 'a worker_live_audit row probed within 6h', 'fm-autoaudit-stale', '2026-09-27', 1351, 'the autoaudit workflow stops', 'worker_live_audit.probed_at older than 6h', 'drift detection for every worker');
INSERT OR IGNORE INTO remediation_contracts (class, issue_id, precondition, action, verify_probe, verify_transport, max_attempts, escalate_to, expected_cadence_h, status, module, budget_ms, max_items, requires_container) VALUES
 ('fm-companion-publish-stall', NULL, 'REACH-FAILURE-MODES-1', 'failure-mode detector', 'SELECT ''1'' AS expected, CASE WHEN CAST((SELECT last_value FROM metric_registry WHERE metric = ''companion_hours_since_last_piece'') AS REAL) < 36 THEN ''1'' ELSE ''0'' END AS observed', 'd1-query', 3, 'qnfo-fleet-control', 1, 'holding', 'failure-mode', 45000, 5, 0),
 ('fm-host-census-stale', NULL, 'REACH-FAILURE-MODES-1', 'failure-mode detector', 'SELECT ''1'' AS expected, CASE WHEN (SELECT COUNT(*) FROM cloud_ops_events WHERE kind = ''host-census'' AND ts > strftime(''%Y-%m-%dT%H:%M:%SZ'', ''now'', ''-12 hours'')) > 0 THEN ''1'' ELSE ''0'' END AS observed', 'd1-query', 3, 'qnfo-fleet-control', 1, 'holding', 'failure-mode', 45000, 5, 0),
 ('fm-social-channel-drain-silent', NULL, 'REACH-FAILURE-MODES-1', 'failure-mode detector', 'SELECT ''1'' AS expected, CASE WHEN (SELECT COUNT(*) FROM cloud_ops_events WHERE kind = ''social-run'' AND text LIKE ''qnfo-social channels ok%'' AND ts > strftime(''%Y-%m-%dT%H:%M:%SZ'', ''now'', ''-5 hours'')) > 0 THEN ''1'' ELSE ''0'' END AS observed', 'd1-query', 3, 'qnfo-fleet-control', 1, 'holding', 'failure-mode', 45000, 5, 0),
 ('fm-autoaudit-stale', NULL, 'REACH-FAILURE-MODES-1', 'failure-mode detector', 'SELECT ''1'' AS expected, CASE WHEN (SELECT COUNT(*) FROM worker_live_audit WHERE probed_at > datetime(''now'', ''-6 hours'')) > 0 THEN ''1'' ELSE ''0'' END AS observed', 'd1-query', 3, 'qnfo-fleet-control', 1, 'holding', 'failure-mode', 45000, 5, 0);
