-- RULE-8-RETIRED-1 (2026-10-06, pillar autonomy). Owner directive: "'Rule 8' is now deleted entirely. The system needs more
-- flexibility and more autonomy to decide for itself and make it's own choices ad hoc. Proceed with all changes." Core prompt
-- rule 8 still lived in D1 as text that doers read: analytics_metric_triggers.action (copied into every METRIC-TRIGGER issue)
-- told them never to raise a spend cap, never to add a model call while a fleet_budget cap is breached (stale since
-- BUDGET-SOFT-ROUTE-1), never to weaken a guard and never to delete without a verified backup. This file rewrites exactly those
-- clauses in 15 trigger actions and appends one note to the open issues that carry the old text. Outreach and posting
-- cadence caps, opt-out lines and IDEA_WIP_MAX are not spend caps and are left as written.
-- Each UPDATE matches its exact old clause with instr(), so a re-run or an already-edited row is a no-op.
-- APPLY-BY: ci
-- DB: qnfo-audit
-- Rollback: UPDATE analytics_metric_triggers SET action = (SELECT b.action FROM bak_amt_rule8_20261006 b WHERE b.metric_key = analytics_metric_triggers.metric_key) WHERE metric_key IN (SELECT metric_key FROM bak_amt_rule8_20261006); UPDATE agent_issues SET description = (SELECT b.description FROM bak_issues_rule8_20261006 b WHERE b.id = agent_issues.id) WHERE id IN (SELECT id FROM bak_issues_rule8_20261006);

CREATE TABLE IF NOT EXISTS bak_amt_rule8_20261006 AS SELECT metric_key, action FROM analytics_metric_triggers WHERE metric_key IN ('attention_events_7d', 'cf_changelog_open_proposals_14d', 'clef_candidate_calls_7d', 'cost_attribution_gap_pct', 'dangling_bindings', 'external_referred_pageviews_7d', 'gateway_cap_30d_usd', 'idea_topic_concentration_30d', 'q08_panel_effective_votes_30d', 'signal_source_families_7d', 'transformation_levers_landed_14d', 'unified_cost_usd_30d', 'warm_conversations_30d', 'worker_count_disagreement');

CREATE TABLE IF NOT EXISTS bak_issues_rule8_20261006 AS SELECT id, description FROM agent_issues WHERE status = 'open' AND instr(description, 'RULE-8-RETIRED-1') = 0 AND (instr(description, 'rule 8') > 0 OR instr(description, 'HARD LIMITS') > 0 OR instr(lower(description), 'never raise a cap') > 0 OR instr(description, 'while a fleet_budget cap is breached') > 0 OR instr(description, 'while fleet_budget ai_spend caps are breached') > 0);

UPDATE analytics_metric_triggers SET action = replace(action, 'Never raise a cap (STRATEGY s4), never add a model call while a fleet_budget cap is breached.', 'Never raise a posting or outreach cadence cap (STRATEGY s4); a breached fleet_budget cap only moves model calls to the cheapest capable model (BUDGET-SOFT-ROUTE-1).') WHERE metric_key = 'attention_events_7d' AND instr(action, 'Never raise a cap (STRATEGY s4), never add a model call while a fleet_budget cap is breached.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Adopt nothing that adds a worker, cron or paid model call while a fleet_budget cap is breached; the decision is then proposed-and-blocked, written down.', 'A breached fleet_budget cap no longer blocks an adoption (RULE-8-RETIRED-1): weigh the measured spend, prefer the cheapest capable model (BUDGET-SOFT-ROUTE-1) and write the decision down.') WHERE metric_key = 'cf_changelog_open_proposals_14d' AND instr(action, 'Adopt nothing that adds a worker, cron or paid model call while a fleet_budget cap is breached; the decision is then proposed-and-blocked, written down.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Net-zero rule 8: the shadow runs on a sample of at most 5 percent.', 'Keep the shadow to a sample of at most 5 percent so the comparison costs little.') WHERE metric_key = 'clef_candidate_calls_7d' AND instr(action, 'Net-zero rule 8: the shadow runs on a sample of at most 5 percent.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never raise a cap (STRATEGY s4) and never add a paid model call while a fleet_budget cap is breached (HARD LIMITS).', 'Changing a spend cap is the fleet''s own decision since RULE-8-RETIRED-1: attribute the cost first, then record the reason and the measured spend on this issue.') WHERE metric_key = 'cost_attribution_gap_pct' AND instr(action, 'Never raise a cap (STRATEGY s4) and never add a paid model call while a fleet_budget cap is breached (HARD LIMITS).') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never delete data without a verified backup, never create the missing resource to silence the count.', 'Back up and read back before deleting data (it costs nothing, D1-FOLD-1), and never create the missing resource only to silence the count.') WHERE metric_key = 'dangling_bindings' AND instr(action, 'Never delete data without a verified backup, never create the missing resource to silence the count.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never buy attention, never raise a cadence cap, never add a model call while a fleet_budget cap is breached.', 'Never buy attention or raise a cadence cap; a breached fleet_budget cap only moves model calls to the cheapest capable model (BUDGET-SOFT-ROUTE-1).') WHERE metric_key = 'external_referred_pageviews_7d' AND instr(action, 'Never buy attention, never raise a cadence cap, never add a model call while a fleet_budget cap is breached.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never raise it.', 'Raising it is the fleet''s own decision since RULE-8-RETIRED-1: record the reason and the measured spend on this issue.') WHERE metric_key = 'gateway_cap_30d_usd' AND instr(action, 'Never raise it.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'once the share allows and no fleet_budget cap is breached;', 'once the share allows;') WHERE metric_key = 'idea_topic_concentration_30d' AND instr(action, 'once the share allows and no fleet_budget cap is breached;') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'While an ai_spend cap is breached triage defers every scorable proposal, so the share moves only as old accepts leave the window.', 'Since idea-hub 1.6.0 (BUDGET-SOFT-ROUTE-1) a breached cap only makes triage score lean, so the share moves with new accepts too.') WHERE metric_key = 'idea_topic_concentration_30d' AND instr(action, 'While an ai_spend cap is breached triage defers every scorable proposal, so the share moves only as old accepts leave the window.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'and do not add a paid provider while fleet_budget ai_spend caps are breached', 'and prefer a free or low-cost provider (BUDGET-SOFT-ROUTE-1)') WHERE metric_key = 'q08_panel_effective_votes_30d' AND instr(action, 'and do not add a paid provider while fleet_budget ai_spend caps are breached') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never add a model call to the intake while a fleet_budget cap is breached.', 'A model call in the intake runs on the cheapest capable model while a fleet_budget cap is breached (BUDGET-SOFT-ROUTE-1).') WHERE metric_key = 'signal_source_families_7d' AND instr(action, 'Never add a model call to the intake while a fleet_budget cap is breached.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never raise a cap, never add a model call while a fleet_budget cap is breached, never weaken a guard to make a lever land.', 'A cap or guard change is the fleet''s own decision since RULE-8-RETIRED-1, recorded with its evidence; never change a guard only to make a lever count as landed.') WHERE metric_key = 'transformation_levers_landed_14d' AND instr(action, 'Never raise a cap, never add a model call while a fleet_budget cap is breached, never weaken a guard to make a lever land.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Otherwise the lever is the owner''s, decided on https://fleet.qnfo.org (INVEST-DECISION-1): the gateway spend limit (gateway_cap_30d_usd) and which clients may bill the gateway credit. Never raise a cap to clear this.', 'Otherwise the levers are the gateway spend limit (gateway_cap_30d_usd) and which clients may bill the gateway credit; since RULE-8-RETIRED-1 the fleet sets the limit itself and records why. Raising the cap only to clear this metric is not a fix.') WHERE metric_key = 'unified_cost_usd_30d' AND instr(action, 'Otherwise the lever is the owner''s, decided on https://fleet.qnfo.org (INVEST-DECISION-1): the gateway spend limit (gateway_cap_30d_usd) and which clients may bill the gateway credit. Never raise a cap to clear this.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never buy attention or raise a cap.', 'Never buy attention or raise an outreach cadence cap.') WHERE metric_key = 'warm_conversations_30d' AND instr(action, 'Never buy attention or raise a cap.') > 0;

UPDATE analytics_metric_triggers SET action = replace(action, 'Never delete a script whose directory has no marker, never raise a cap (STRATEGY s4).', 'Never delete a script whose directory has no marker.') WHERE metric_key = 'worker_count_disagreement' AND instr(action, 'Never delete a script whose directory has no marker, never raise a cap (STRATEGY s4).') > 0;

UPDATE agent_issues SET description = description || '
(RULE-8-RETIRED-1, 2026-10-06: the owner deleted core prompt rule 8. Clauses above that forbid raising a spend cap, adding a model call while a fleet_budget cap is breached, changing a guard or probe, or deleting without a backup no longer bind; those are the fleet''s own decisions, recorded with the reason and a live measurement. Email opt-out and suppression, outreach consent and cadence caps, and the personal/research separation still hold.)' WHERE status = 'open' AND instr(description, 'RULE-8-RETIRED-1') = 0 AND (instr(description, 'rule 8') > 0 OR instr(description, 'HARD LIMITS') > 0 OR instr(lower(description), 'never raise a cap') > 0 OR instr(description, 'while a fleet_budget cap is breached') > 0 OR instr(description, 'while fleet_budget ai_spend caps are breached') > 0);
