-- OUTREACH-LEARNER-1 metrics (2026-10-02, pillar: reach). qnfo-cloud-ops 1.18.0 computes two metrics daily (job
-- outreach-learner, a companion in the engagement slot) and writes them to metric_registry. METRIC-CLOSED-LOOP-1
-- (CLAUDE.md): a change that registers a metric also adds its trigger, so this file registers both rows (identical to
-- LEARNER_METRICS in qnfo-cloud-ops/worker.js, which only INSERT OR IGNOREs them on a fresh database) and adds one
-- analytics_metric_triggers row each. Idempotent (safe to re-run); an existing row of either kind is left alone.
--
-- outreach_reply_rate_30d: percent of first-contact cold emails sent in the last 30 days by both engines that drew a
--   positive reply (a human reply, same address or same thread, that is not an auto-reply, an opt-out or a decline).
--   Written as 'n/a' under 20 first contacts, which v_metric_trigger_state and evaluateMetricTriggers read as
--   unreadable, never as 0, so a paused stream fires nothing. Baseline 4.1% (13 replies of any kind to 318 cold emails
--   up to 2026-10-01, docs/STRATEGY.md s1). Trigger: under 2%.
-- warm_conversations_30d: distinct people who replied positively in the last 30 days, plus inbound contacts (a first,
--   non-automated, non-bulk, non-solicitation message to rowan.quni@qnfo.org from an address the fleet never wrote to,
--   that is not a reply; mail tagged [work-with-me:<offer>] from qnfo.org/work-with-me always counts, and the dashboard's
--   inbound_contacts_30d (WORK-WITH-ME-METRIC-1) counts those tagged contacts alone). Target 10 new by 2026-12-31
--   (docs/STRATEGY.md s9), about 3-4 a month. Trigger: under 2.
-- The per-segment rule (a segment under 1% after 50 sends stops) is enforced in code, not by a trigger.

INSERT OR IGNORE INTO metric_registry (metric, layer, kind, formula, source_of_truth, baseline, target, owner, disposition_actor, refresh_cadence, warning_band, kill_band, state) VALUES
 ('outreach_reply_rate_30d', 'fleet', 'lagging', 'percent of first-contact cold emails sent in the last 30 days by both engines (qnfo-audit.outreach_log, qnfo-outreach.sends; one per address) that drew a positive reply: a human reply from the same address or thread that is not an auto-reply, an opt-out or a decline; n/a under 20 first contacts (OUTREACH-LEARNER-1)', 'qnfo-audit.outreach_log + qnfo-outreach.sends + qnfo-audit.emails (qnfo-cloud-ops outreach-learner, daily)', '4.1 (13 replies of any kind to 318 cold emails up to 2026-10-01, docs/STRATEGY.md s1)', '>= 2 overall; every live segment >= 1% (a segment under 1% after 50 sends stops, docs/STRATEGY.md s6.4)', 'qnfo-cloud-ops', 'OUTREACH-LEARNER-1 (qnfo-cloud-ops): Thompson allocation of the shared 8/day cold-email cap toward segments that answer; a segment under 1% after 50 sends stops', 'daily', '< 2', '< 1', 'MEASURED'),
 ('warm_conversations_30d', 'fleet', 'leading', 'distinct people in the last 30 days who replied positively to mail the fleet sent, plus inbound contacts: a first non-automated, non-bulk, non-solicitation message to rowan.quni@qnfo.org from an address the fleet never wrote to, that is not a reply, and any mail tagged [work-with-me:<offer>] (inbound_contacts_30d counts those alone) (OUTREACH-LEARNER-1)', 'qnfo-audit.emails + outreach_log + contact_ledger + qnfo-outreach.contacts (qnfo-cloud-ops outreach-learner, daily)', '13 replies to date on 2026-10-01 (docs/STRATEGY.md s9)', '>= 4 per 30 days (10 new by 2026-12-31, docs/STRATEGY.md s9)', 'qnfo-cloud-ops', 'OUTREACH-LEARNER-1 (qnfo-cloud-ops): Thompson allocation of the shared 8/day cold-email cap toward segments that answer; a segment under 1% after 50 sends stops', 'daily', '< 2', '< 1', 'MEASURED');

WITH v(metric_key, title, source_table, operator, threshold, priority, action, owner, cooldown) AS (VALUES
  ('outreach_reply_rate_30d', 'Reach gap: cold-email positive reply rate under 2% over 30 days', 'registry', 'lt', 2, 7, 'Pillar reach. Fewer than 2% of first-contact cold emails sent in the last 30 days drew a positive reply. Levers, in order: (1) read outreach_learner_arms and the latest cloud_ops_events ol-alloc-* rows and check the learner is on (ops_config outreach_learner_enabled absent or 1) and holding stopped segments; (2) check what the candidates are: if outreach_queue is mostly segments with the weakest posteriors, move the candidate source toward the segment that answers (radar-hub arXiv keyword classes toward energy and JPCUB papers, idea-triage cited-author matches); (3) if every live segment is weak, the first-contact text is the lever: add a second template variant as a new learner dimension (a code-task for qnfo-cloud-ops/worker.js jobOutreach and LEARNER_TEMPLATE) and fix the identity line it carries (docs/STRATEGY.md s2.1); (4) check replies are being read: qnfo-email storing rowan.quni@qnfo.org mail and outreach_learner_sends outcomes resolving. Never raise the 8/day or 3/day-per-domain caps, never drop the opt-out line.', 'qnfo-cloud-ops', 168),
  ('warm_conversations_30d', 'Reach gap: fewer than 2 warm conversations in 30 days', 'registry', 'lt', 2, 6, 'Pillar reach. Fewer than 2 people replied positively or wrote in first in 30 days. Levers, in order: (1) is outreach sending at all (qnfo-outreach pipeline_state.external_sends_enabled, outreach_queue rows with an address, the shared cap not exhausted by self-checks)? (2) are positive replies being answered: email_reply_queue rows with decision escalate and no draft_text are conversations the fleet let lapse; author the replies through the owner-voice gates; (3) are the selected works reachable from every outreach mail and post (docs/STRATEGY.md s2.4), so a reader has a reason to write; (4) apply the outreach_reply_rate_30d levers. Never buy attention or raise a cap.', 'qnfo-cloud-ops', 168)
)
INSERT OR IGNORE INTO analytics_metric_triggers (metric_key, title, source_table, operator, threshold, priority, action, owner, queue_target, cooldown_hours, enabled, notes)
SELECT v.metric_key, v.title, v.source_table, v.operator, v.threshold, v.priority, v.action || ' Definition of done: the metric is back inside its threshold in metric_registry; record the before and after values in issue_triage.close_evidence. If the remedy you try does not move the metric within 7 days, say so on the issue and try a different lever (remedy_efficacy_30d counts it).', v.owner, 'agent_issues', v.cooldown, 1, 'METRIC-CLOSED-LOOP-1 + OUTREACH-LEARNER-1 2026-10-02'
FROM v
WHERE NOT EXISTS (SELECT 1 FROM analytics_metric_triggers x WHERE x.metric_key = v.metric_key AND x.enabled = 1);
