// qnfo-fleet-dashboard registry - generated by ops cycle 2026-09-07 (P1 inventory)
// Schedules: CF Workers API /schedules; purposes curated; device-bound: schtasks live capture
export const REGISTRY = {
 "version": 1,
 "captured_at": "2026-09-07T17:42:00Z",
 "note": "Schedules from CF Workers API 2026-09-07; purposes curated; device-bound captured live from this host",
 "scheduled": [
  {
   "name": "calendar-api",
   "crons": [
    "17 * * * *"
   ],
   "purpose": "Calendar/email intent sync",
   "group": "intent-email",
   "modified_on": "2026-09-03T04:46:55.755286Z"
  },
  {
   "name": "events-radar",
   "crons": [
    "0 5 * * 1"
   ],
   "purpose": "Weekly research events radar",
   "group": "engagement",
   "modified_on": "2026-09-02T11:14:48.653431Z"
  },
  {
   "name": "jnl-referee",
   "crons": [
    "23 */2 * * *"
   ],
   "purpose": "Journal referee queue (intake/submissions)",
   "group": "research-publish",
   "modified_on": "2026-09-07T17:30:00.440211Z"
  },
  {
   "name": "jnl-watch",
   "crons": [
    "*/10 * * * *"
   ],
   "purpose": "Journal listings watch",
   "group": "research-publish",
   "modified_on": "2026-09-06T11:58:02.718732Z"
  },
  {
   "name": "job-market-watch",
   "crons": [
    "0 7 * * 2"
   ],
   "purpose": "Academic job market radar",
   "group": "engagement",
   "modified_on": "2026-09-01T11:28:57.540759Z"
  },
  {
   "name": "osf-integrity-check",
   "crons": [
    "0 9 1 * *"
   ],
   "purpose": "OSF integrity sweep",
   "group": "research-publish",
   "modified_on": "2026-09-01T11:56:24.297281Z"
  },
  {
   "name": "personal-api",
   "crons": [
    "5 5 * * *"
   ],
   "purpose": "Personal twin daily maintenance",
   "group": "personal",
   "modified_on": "2026-09-05T20:47:36.261572Z"
  },
  {
   "name": "personal-events-radar",
   "crons": [
    "30 5 * * 2"
   ],
   "purpose": "Personal events radar",
   "group": "personal",
   "modified_on": "2026-09-03T04:46:37.651045Z"
  },
  {
   "name": "personal-life-indexer",
   "crons": [
    "0 */12 * * *"
   ],
   "purpose": "Personal life index refresh",
   "group": "personal",
   "modified_on": "2026-08-20T17:19:11.088746Z"
  },
  {
   "name": "personal-life-maintain",
   "crons": [
    "0 2 * * *"
   ],
   "purpose": "Personal knowledge maintenance",
   "group": "personal",
   "modified_on": "2026-09-01T07:27:59.931823Z"
  },
  {
   "name": "qnfo-ai-calibration",
   "crons": [
    "*/30 * * * *"
   ],
   "purpose": "AI model calibration probes",
   "group": "fleet-ai",
   "modified_on": "2026-09-06T08:14:43.613421Z"
  },
  {
   "name": "qnfo-analytics",
   "crons": [
    "15 6 * * *"
   ],
   "purpose": "Fleet analytics daily snapshot",
   "group": "fleet-ops",
   "modified_on": "2026-09-05T20:19:58.04525Z"
  },
  {
   "name": "qnfo-archive",
   "crons": [
    "0 4 * * *"
   ],
   "purpose": "Archive sweep",
   "group": "fleet-ops",
   "modified_on": "2026-07-30T12:05:58.320447Z"
  },
  {
   "name": "qnfo-arxiv-radar",
   "crons": [
    "30 8 * * *"
   ],
   "purpose": "arXiv radar daily",
   "group": "research-publish",
   "modified_on": "2026-09-01T18:02:45.962281Z"
  },
  {
   "name": "qnfo-auditor",
   "crons": [
    "45 1,13 * * *",
    "45 6 * * 1"
   ],
   "purpose": "Fleet auditor (2x daily + weekly)",
   "group": "fleet-ops",
   "modified_on": "2026-09-04T02:07:58.107269Z"
  },
  {
   "name": "qnfo-backlog-exec",
   "crons": [
    "10 1 * * *"
   ],
   "purpose": "Deferred backlog executor",
   "group": "fleet-ops",
   "modified_on": "2026-09-02T18:31:50.7745Z"
  },
  {
   "name": "qnfo-blank-audit",
   "crons": [
    "40 4 * * *"
   ],
   "purpose": "Blank/empty audit sweep",
   "group": "fleet-ops",
   "modified_on": "2026-09-02T20:34:47.549905Z"
  },
  {
   "name": "qnfo-chat-canary",
   "crons": [
    "15 */3 * * *",
    "30 6 * * *"
   ],
   "purpose": "Chat canary probes",
   "group": "fleet-ai",
   "modified_on": "2026-09-03T04:57:33.036401Z"
  },
  {
   "name": "qnfo-citation-watch",
   "crons": [
    "0 11 1,15 * *"
   ],
   "purpose": "Citation watch (2x monthly)",
   "group": "engagement",
   "modified_on": "2026-09-03T05:51:42.890352Z"
  },
  {
   "name": "qnfo-cloud-ops",
   "crons": [
    "0 15 * * 5",
    "0 4 * * 7",
    "0 6 * * 1",
    "0 6 * * 6",
    "0 6,12 * * 1-5",
    "0 7 * * 7",
    "0 7,13 * * 1-5",
    "0 8 * * 1-5",
    "0 9 * * 1-5",
    "0 9 3 9 *",
    "15 4 * * *",
    "15 5 * * 1",
    "30 5 * * 1",
    "30 6 * * 1-5",
    "35 3 * * *",
    "5 3 * * *"
   ],
   "purpose": "Cloud ops weekly digests + lifecycle",
   "group": "fleet-ops",
   "modified_on": "2026-09-06T07:50:13.758635Z"
  },
  {
   "name": "qnfo-ddocs-indexer",
   "crons": [
    "37 */2 * * *"
   ],
   "purpose": "Deep-docs indexer",
   "group": "research-publish",
   "modified_on": "2026-09-04T09:55:53.595087Z"
  },
  {
   "name": "qnfo-email-orchestrator",
   "crons": [
    "0 */3 * * *"
   ],
   "purpose": "Email intent orchestration",
   "group": "intent-email",
   "modified_on": "2026-09-03T13:38:46.239983Z"
  },
  {
   "name": "qnfo-errata-publish",
   "crons": [
    "30 * * * *"
   ],
   "purpose": "Errata autopublish",
   "group": "research-publish",
   "modified_on": "2026-09-04T14:40:11.345189Z"
  },
  {
   "name": "qnfo-errata-respond",
   "crons": [
    "15 * * * *"
   ],
   "purpose": "Errata response",
   "group": "research-publish",
   "modified_on": "2026-09-03T13:38:10.933637Z"
  },
  {
   "name": "qnfo-errata-watch",
   "crons": [
    "0 * * * *"
   ],
   "purpose": "Errata watch",
   "group": "research-publish",
   "modified_on": "2026-09-03T13:38:14.718097Z"
  },
  {
   "name": "qnfo-error-selfheal",
   "crons": [
    "17 * * * *"
   ],
   "purpose": "Error self-heal loop",
   "group": "fleet-ops",
   "modified_on": "2026-09-06T20:50:21.971742Z"
  },
  {
   "name": "qnfo-events",
   "crons": [
    "15 */6 * * *"
   ],
   "purpose": "Events processing",
   "group": "engagement",
   "modified_on": "2026-09-04T02:04:15.974811Z"
  },
  {
   "name": "qnfo-fleet-calibrator",
   "crons": [
    "0 3 * * *",
    "0 4 1 * *",
    "30 3 * * 1"
   ],
   "purpose": "Fleet calibration",
   "group": "fleet-ops",
   "modified_on": "2026-09-04T05:10:58.967275Z"
  },
  {
   "name": "qnfo-idea-miner",
   "crons": [
    "0 * * * *"
   ],
   "purpose": "Idea mining",
   "group": "engagement",
   "modified_on": "2026-09-03T13:37:06.422634Z"
  },
  {
   "name": "qnfo-idea-triage",
   "crons": [
    "*/10 * * * *",
    "0 * * * *"
   ],
   "purpose": "Idea triage",
   "group": "engagement",
   "modified_on": "2026-09-06T21:00:11.897514Z"
  },
  {
   "name": "qnfo-impact",
   "crons": [
    "0 4 * * *"
   ],
   "purpose": "Impact metrics",
   "group": "engagement",
   "modified_on": "2026-09-01T09:56:57.809672Z"
  },
  {
   "name": "qnfo-infra",
   "crons": [
    "0 18 * * *",
    "30 6 * * *"
   ],
   "purpose": "Infra state snapshots",
   "group": "fleet-ops",
   "modified_on": "2026-09-05T20:44:04.55895Z"
  },
  {
   "name": "qnfo-intent-orchestrator",
   "crons": [
    "0 6 * * *",
    "30 6 * * *"
   ],
   "purpose": "Intent digest/routing",
   "group": "intent-email",
   "modified_on": "2026-09-05T20:47:40.888348Z"
  },
  {
   "name": "qnfo-kaizen",
   "crons": [
    "0 10 * * 1",
    "0 2 * * *"
   ],
   "purpose": "Kaizen watchtower + meta loop",
   "group": "fleet-ops",
   "modified_on": "2026-09-04T13:48:43.3678Z"
  },
  {
   "name": "qnfo-lifecycle",
   "crons": [
    "*/30 * * * *",
    "0 * * * *",
    "0 0 1 * *",
    "0 3 * * *",
    "0 4 * * *",
    "0 5 * * *",
    "0 6 * * *",
    "0 7 * * *",
    "0 8 * * 1"
   ],
   "purpose": "Lifecycle scheduled ops",
   "group": "fleet-ops",
   "modified_on": "2026-09-01T07:12:40.986974Z"
  },
  {
   "name": "qnfo-ops",
   "crons": [
    "*/30 * * * *"
   ],
   "purpose": "Ops AI gateway health loop",
   "group": "fleet-ai",
   "modified_on": "2026-09-06T11:51:07.143291Z"
  },
  {
   "name": "qnfo-outreach",
   "crons": [
    "0 11 * * 1-5"
   ],
   "purpose": "Outreach campaign engine",
   "group": "engagement",
   "modified_on": "2026-09-02T22:32:56.771754Z"
  },
  {
   "name": "qnfo-paper-indexer",
   "crons": [
    "0 6 * * *"
   ],
   "purpose": "Paper indexer",
   "group": "research-publish",
   "modified_on": "2026-08-12T13:07:52.596336Z"
  },
  {
   "name": "qnfo-paper-reviser",
   "crons": [
    "37 */4 * * *"
   ],
   "purpose": "Publication reviser loop",
   "group": "research-publish",
   "modified_on": "2026-09-06T20:49:21.524837Z"
  },
  {
   "name": "qnfo-pipeline-ops",
   "crons": [
    "*/15 * * * *"
   ],
   "purpose": "Pipeline ops watchdog",
   "group": "fleet-ops",
   "modified_on": "2026-09-06T20:49:21.36612Z"
  },
  {
   "name": "qnfo-research-exec",
   "crons": [
    "*/10 * * * *"
   ],
   "purpose": "Research version_queue drain",
   "group": "research-publish",
   "modified_on": "2026-09-06T21:00:11.723528Z"
  },
  {
   "name": "qnfo-research-radar",
   "crons": [
    "0 6 1 * *",
    "0 8 * * 7",
    "0 9 * * 7"
   ],
   "purpose": "Research radar",
   "group": "research-publish",
   "modified_on": "2026-09-01T17:45:42.480341Z"
  },
  {
   "name": "qnfo-skill-sync",
   "crons": [
    "0 3 * * *"
   ],
   "purpose": "Skill sync",
   "group": "fleet-ops",
   "modified_on": "2026-09-03T13:39:39.932797Z"
  },
  {
   "name": "qnfo-social",
   "crons": [
    "0 16 * * *",
    "0 6 * * *",
    "0 7 * * *",
    "0 9 * * *",
    "30 14 * * *"
   ],
   "purpose": "Social amplifier queue",
   "group": "engagement",
   "modified_on": "2026-09-04T12:14:53.555691Z"
  },
  {
   "name": "qnfo-system-health",
   "crons": [
    "0 5 * * *"
   ],
   "purpose": "System health daily",
   "group": "fleet-ops",
   "modified_on": "2026-09-06T20:38:41.736509Z"
  },
  {
   "name": "qnfo-twin-maintain",
   "crons": [
    "0 4 * * *"
   ],
   "purpose": "Personal twin maintain",
   "group": "personal",
   "modified_on": "2026-09-01T07:50:03.966557Z"
  },
  {
   "name": "qnfo-venue-radar",
   "crons": [
    "45 6 * * *"
   ],
   "purpose": "Venue radar",
   "group": "research-publish",
   "modified_on": "2026-09-03T17:59:03.476834Z"
  },
  {
   "name": "research-daily-brief",
   "crons": [
    "0 6 * * *"
   ],
   "purpose": "Daily research brief send",
   "group": "research-publish",
   "modified_on": "2026-09-02T08:32:20.47738Z"
  }
 ],
 "windows_tasks": [
  {
   "name": "QNFO-ModelKey-Guard",
   "status": "Ready",
   "last": "9/7/2026 7:25:01 PM",
   "lastres": "0",
   "next": "9/7/2026 7:55:00 PM",
   "schedule": "Minute (every 30)"
  },
  {
   "name": "QNFO-DeepChat-Backup",
   "status": "Ready",
   "last": "9/7/2026 9:19:54 AM",
   "lastres": "-2147020576",
   "next": "9/8/2026 6:45:00 AM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO-AgentDB-Daily-Backup",
   "status": "Ready",
   "last": "9/6/2026 9:30:01 PM",
   "lastres": "0",
   "next": "9/7/2026 9:30:00 PM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO_DeepChat_Backup_Daily",
   "status": "Ready",
   "last": "9/7/2026 3:54:46 PM",
   "lastres": "-2147020576",
   "next": "9/8/2026 9:30:00 AM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO_Snapshot_Purge",
   "status": "Ready",
   "last": "9/7/2026 4:34:52 AM",
   "lastres": "-2147020576",
   "next": "9/8/2026 3:00:00 AM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO_Skill_Pull_Daily",
   "status": "Ready",
   "last": "9/7/2026 9:19:54 AM",
   "lastres": "-2147020576",
   "next": "9/8/2026 6:30:00 AM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO_Chat_Log_Push",
   "status": "Ready",
   "last": "9/7/2026 9:19:54 AM",
   "lastres": "-2147020576",
   "next": "9/8/2026 5:25:00 AM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO_Tape_Prune_Daily",
   "status": "Ready",
   "last": "9/7/2026 9:19:54 AM",
   "lastres": "-2147020576",
   "next": "9/8/2026 5:35:00 AM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO_FS_Maintenance_Daily",
   "status": "Ready",
   "last": "9/7/2026 3:54:46 PM",
   "lastres": "1",
   "next": "9/8/2026 9:40:00 AM",
   "schedule": "Daily"
  },
  {
   "name": "QNFO_DeepChat_Reload",
   "status": "Ready",
   "last": "9/7/2026 7:36:01 PM",
   "lastres": "0",
   "next": "9/7/2026 7:46:00 PM",
   "schedule": "Minute (every 10)"
  },
  {
   "name": "QNFO_Obsidian_Sync",
   "status": "Ready",
   "last": "9/7/2026 7:38:01 PM",
   "lastres": "3",
   "next": "9/7/2026 7:53:00 PM",
   "schedule": "Minute (every 15)"
  },
  {
   "name": "QNFO_Obsidian_Cloud_Bridge",
   "status": "Disabled",
   "last": "11/30/1999",
   "lastres": "267011",
   "next": "N/A",
   "schedule": "Daily"
  }
 ],
 "local_crons": [
  {
   "id": "aa67d355",
   "name": "QNFO Data Freshness Sync (calendar/email to orchestrator)",
   "cron": "12 5 * * *",
   "note": "canonical row 1"
  },
  {
   "id": "42b1988c",
   "name": "Fleet Drift and Self-Improvement Audit",
   "cron": "30 5 * * 1",
   "note": "canonical row 2"
  },
  {
   "id": "c7f96688",
   "name": "Local config/credential guard",
   "cron": "device-triggered",
   "note": "canonical row 3"
  },
  {
   "id": "2055e49c",
   "name": "Device-bound maintenance one-shot",
   "cron": "one-shot",
   "note": "canonical row 4"
  },
  {
   "id": "6e91c844",
   "name": "Front-end local cron mirror guard",
   "cron": "device-triggered",
   "note": "canonical row 5"
  }
 ],
 "health_probes": [
  {
   "name": "qnfo-ai",
   "url": "https://qnfo-ai.q08.workers.dev/health",
   "binding": "SVC_QNFO_AI"
  },
  {
   "name": "personal-api",
   "url": "https://personal-api.q08.workers.dev/health",
   "binding": "SVC_PERSONAL_API"
  },
  {
   "name": "qnfo-ops",
   "url": "https://qnfo-ops.q08.workers.dev/health",
   "binding": "SVC_QNFO_OPS"
  },
  {
   "name": "qnfo-kaizen",
   "url": "https://qnfo-kaizen.q08.workers.dev/health",
   "binding": "SVC_QNFO_KAIZEN"
  },
  {
   "name": "qnfo-paper-reviser",
   "url": "https://qnfo-paper-reviser.q08.workers.dev/health",
   "binding": "SVC_QNFO_PAPER_REVISER"
  },
  {
   "name": "papers.qnfo.org",
   "url": "https://papers.qnfo.org/"
  },
  {
   "name": "qnfo.org",
   "url": "https://qnfo.org/health",
   "binding": "SVC_QNFO_GATEWAY"
  },
  {
   "name": "qnfo-social",
   "url": "https://qnfo-social.q08.workers.dev/health",
   "binding": "SVC_QNFO_SOCIAL"
  },
  {
   "name": "qnfo-outreach",
   "url": "https://qnfo-outreach.q08.workers.dev/health",
   "binding": "SVC_QNFO_OUTREACH"
  },
  {
   "name": "personal-events-radar",
   "url": "https://personal-events-radar.q08.workers.dev/health",
   "binding": "SVC_PERSONAL_EVENTS_RADAR"
  }
 ]
};


