-- QRI-1b — SUPERSEDED. DO NOT RUN THIS FILE.
-- Author: qnfo-ops, 2026-09-13. Superseded the same day it was committed.
--
-- Superseded by:
--   sql/QRI-2-body-corrections-2026-09-13.sql    (the body_md correction)
--   sql/QRI-3-feedback-provenance-2026-09-13.sql (the provenance partition)
--
-- WHY THIS FILE MUST NOT BE EXECUTED, most severe first.
--
-- 1. IT WOULD DROP TWO REAL READER SIGNALS.
--    Section B2/B3 tagged companion_feedback ids 46 and 47 as 'review' on a timing-only
--    argument (5.769 s apart, same slug). QRI-3 decides the same rows with a second,
--    independent signal: both point at a REAL companion_pieces row, while all 42 machine
--    rows point at slugs that were never published. The partition {1-42 probe} /
--    {43-48 human} is confirmed by two agreeing signals; timing alone could not settle it.
--    Running B3 after QRI-3 would overwrite 'human' with 'review' and drop two genuine
--    signals from loadContinuity() — the exact defect that section was written to fix.
--    My inference was wrong.
--
-- 2. IT MISSES A SECOND STANDING-FILTER VIOLATION.
--    Section A checked only the string 'Quantum Programming Languages' (instr = 392).
--    The bare token 'QPL' occurs TWICE. Verified by qnfo-ops against PERSONAL.body_md,
--    2026-09-13:
--      instr(body_md,'QPL')                                       = 352
--      instr(substr(body_md, instr(body_md,'QPL')+1),'QPL')       = 13602  -> abs 13954
--      instr(body_md,'the QPL 2026 room')                         = 13950
--    QRI-2 step 2b closes the second occurrence. This file does not, so it would have
--    shipped text still naming what the reader asked not to be sent.
--
-- 3. IT WOULD CORRUPT QRI-2's word_count.
--    If A2 here ran BEFORE QRI-2 step 1, QRI-2's step-1 anchor is destroyed and that step
--    silently no-ops; QRI-2 step 3 then writes a literal word_count describing a body that
--    no longer exists. Do not interleave the two files.
--
-- 4. A2's replacement here is inferior.
--    QRI-2 replaces the whole two-sentence span, which avoids both the duplicated duration
--    ("ran five days") and the duplicated name ("LoF26 ... The occasion was LoF26") that a
--    single-sentence replacement produces. My rev 2 patched that by weakening the sentence
--    to "the conference"; QRI-2 solves it properly.
--
-- ONE FINDING HERE IS IN NEITHER QRI-2 NOR QRI-3. Carry it forward.
--   The A1 replacement text — adopted verbatim by QRI-2 step 2 — deletes "a status
--   tournament" along with the false material. That phrase is RECORD-SUPPORTED:
--   PERSONAL.events, id='evt-qpl26', notes = "Epistemic rigidity; motive currency =
--   status. Draining despite local." Dropping it removes a true characterisation the
--   piece's own argument leans on ("a status tournament has a task for every minute").
--   "with proceedings and citations" is in no record row and should stay dropped.
--   Variant retaining only the supported part, as QRI-2 step 2's replacement:
--     'The record logs the first week 5 out of 5 for felt energy and the second 1 out of
--      5. It records the second as a status tournament. The two events were seven days
--      apart, not consecutive, and the record holds no cost for either.'
--   Operator's call. Dropping it is defensible; the loss should be deliberate, not silent.
--
-- DISCREPANCY BETWEEN THE SUPERSEDING FILES — RESOLVED 2026-09-13 by qnfo-ops.
--   QRI-2 §3:    word_count 2503, length 15276   <- CORRECT
--   QRI-3 §4(a): word_count 2504, length 15278   <- WRONG, by 1 word and 2 characters
--
--   Recomputed from the span literals using worker.js's own wordCount() rule (runs of
--   non-whitespace), against the stored base 2539 words / 15517 chars:
--     QRI-2 span 1, chars    1..287   opening span   49 words -> 31   delta -18
--     QRI-2 span 2, chars  289..575   Rowan span     54 words -> 37   delta -17
--     QRI-2 span 3                    closing name    4 words ->  3   delta  -1
--     total -36   ->  word_count 2503
--     char deltas: -132, -107, -2  =  -241   ->  length 15276
--
--   QRI-3's 2504 implies a total delta of -35, which these spans cannot produce: the
--   4->3 replacement alone is -1, and -18 and -17 are exact. QRI-2 step 3's literal 2503
--   is therefore right. Do NOT "correct" it to 2504 on the strength of QRI-3 §4(a).
--   Caveat, stated: this inherits the stored 2539 as its base. If the stored value was
--   already wrong the absolute result shifts, but the delta -36 is unaffected either way.
--
-- INDEPENDENTLY VERIFIED BY qnfo-ops (2026-09-13), against the raw column:
--   before-state agrees with both files: length(body_md) = 15517, word_count = 2539
--   QRI-2's anchors byte-match:  instr(body_md, <A1 span>) = 289
--                                instr(body_md, <two-sentence opening span>) = 1
--   instr(body_md,'Quantum Physics and Logic') = 0 — the expansion is absent from the
--                                body, as both files state; QRI-3 §4b holds the verified
--                                expansion from qpl2026.github.io if it is to be restored.
--
-- No executable statements remain in this file. Use QRI-2 and QRI-3.
