// FOLD-KIT-1 suite for calendar-api folded into qnfo-lifecycle (generated by scripts/fold_worker.py; edit the kit, not this file).
// Proves: every calendar-api line runs unchanged in the host except its imports, its VERSION line, its export and a bundler's
// sourceMappingURL trailer; one top-level quoted
// VERSION constant; GET /calendar/health answers as the member; a service binding whose props name the member with a
// qnfo-* caller (or a named one) reaches it, any other caller or path reaches the host; public routes keep their method,
// query and body and carry no binding props; derived env values are HMACs of a host secret the member never sees; on a host
// tick the member's due job runs with the mapped env as a table entry and is awaited, next to the host's own scheduled work.
// Run: node --no-warnings qnfo-lifecycle/calendar-api-fold.test.mjs   -> prints "N passed, 0 failed"
import { readFileSync } from "node:fs";
const src = readFileSync(new URL("./worker.js", import.meta.url), "utf8");
const guest = readFileSync(new URL("../calendar-api/worker.js", import.meta.url), "utf8");
// cloudflare:* modules do not exist under node: each imported name becomes an empty function (extendable and callable).
const stubbed = src.replace(/^import \{([^}]*)\} from "cloudflare:[^"]+";$/gm, (_, names) => names.split(",").map((n) => n.trim()).filter(Boolean).map((n) => { const p = n.split(/\s+as\s+/); return "function " + (p[1] || p[0]).trim() + "() {}"; }).join("\n"));
const mod = await import("data:text/javascript;base64," + Buffer.from(stubbed + "\nexport { calendarApiFoldMod as __member, __fk_calendarApi_default as __wrapped, VERSION as __hv, CALENDAR_API_FOLD_VERSION as __mv };\n").toString("base64"));
let pass = 0, fail = 0;
const ok = (c, m, x) => { if (c) pass++; else { fail++; console.log("FAIL " + m + (x !== undefined ? " :: " + JSON.stringify(x).slice(0, 300) : "")); } };
{
  const lines = guest.split("\n");
  const exportAt = lines.findIndex((l) => l === "export {" || l === "export default {");
  const missing = lines.filter((l, i) => l.trim() && !src.includes(l.trim()) && !l.startsWith("import ") && !l.startsWith("//# sourceMappingURL") && !/^var VERSION = "/.test(l) && !(exportAt >= 0 && i >= exportAt && (l === "export {" || /^\s+\w+ as default$/.test(l) || l === "};" || l === "export default {")));
  ok(missing.length === 0, "every calendar-api line is in the host except its imports, VERSION line and export", missing.map((l) => l.slice(0, 80)));
  ok((src.match(/^var VERSION = "/gm) || []).length === 1 && /^1\.(9|[1-9]\d)\.\d+-/.test(mod.__hv) && mod.__mv === "0.7.5-folded", "host 1.9.x or later (was pinned to 1.9.0-calendar-fold; RETIRED-HOSTS-1 bumps it), member 0.7.5-folded, one top-level quoted VERSION constant", [mod.__hv, mod.__mv]);
}
const W = mod.__wrapped, M = mod.__member, H = W.__foldHost;
const calls = [];
const real = { mf: M.fetch, ms: M.scheduled, hf: H.fetch, hs: H.scheduled };
M.fetch = async (req, env, ctx) => { calls.push({ who: "member", path: new URL(req.url).pathname, search: new URL(req.url).search, env, method: req.method, body: req.method === "GET" || req.method === "HEAD" ? null : await req.text(), props: ctx && ctx.props }); return new Response("m"); };
H.fetch = async (req) => { calls.push({ who: "host", path: new URL(req.url).pathname }); return new Response("h"); };
const env = { QNFO_AUDIT: { tag: "QNFO_AUDIT" }, __HOST_ONLY__: { tag: "__HOST_ONLY__" }, CF_API_TOKEN: "secret-CF_API_TOKEN" };
{
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/calendar/health"), env, {});
  ok(calls.length === 1 && calls[0].who === "member" && calls[0].path === "/health", "GET /calendar/health answers as the member", calls);
  calls.length = 0;
  await W.fetch(new Request("https://internal/any/route", { method: "POST", body: "{}" }), env, { props: { caller: "qnfo-ops", member: "calendar-api" } });
  ok(calls.length === 1 && calls[0].who === "member" && calls[0].path === "/any/route", "a binding whose props name the member reaches it", calls);
  ok(calls[0] && calls[0].env.CAL_DB === env.QNFO_AUDIT, "the member gets QNFO_AUDIT as CAL_DB");
  ok(calls[0] && !("__HOST_ONLY__" in calls[0].env), "the member env carries only its own names (least privilege), not the host's other bindings", calls[0] && Object.keys(calls[0].env));
  calls.length = 0;
  await W.fetch(new Request("https://internal/any/route", { method: "POST", body: "{}" }), env, { props: { caller: "evil", member: "calendar-api" } });
  ok(calls.length === 1 && calls[0].who === "host", "props with a caller outside qnfo-* reach the host, not the member", calls);
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/any/route"), env, {});
  ok(calls.length === 1 && calls[0].who === "host", "a public request outside the member's prefix reaches the host", calls);
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/calendar/health"), env, { props: { caller: "qnfo-ops" } });
  ok(calls[0] && calls[0].who === "member" && !(calls[0].props && calls[0].props.caller), "a public request reaches the member without binding props", calls);
  calls.length = 0;
  await W.fetch(new Request("https://internal/x"), env, { props: { caller: "personal-api", member: "calendar-api" } });
  ok(calls.length === 1 && calls[0].who === "member", "the named caller personal-api reaches the member", calls);
  calls.length = 0;
  await W.fetch(new Request("https://internal/x"), env, { props: { caller: "radar-hub", member: "calendar-api" } });
  ok(calls.length === 1 && calls[0].who === "member", "the named caller radar-hub reaches the member", calls);
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/calendar/e/7?s=1", { method: "GET" }), env, { props: { caller: "qnfo-ops", member: "other" } });
  ok(calls.length === 1 && calls[0].who === "member" && calls[0].path === "/e/7" && calls[0].search === "?s=1" && calls[0].method === "GET" && (calls[0].body === null || calls[0].body === "a=keep") && !(calls[0].props && calls[0].props.caller), "GET /calendar/e/7 reaches the member with its query, body and no binding props", calls);
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/calendar/e/7", { method: "DELETE", body: "x" }), env, {});
  ok(calls.length === 1 && calls[0].who === "host", "DELETE /calendar/e/7 is not a member route", calls);
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/calendar/e/"), env, {});
  ok(calls.length === 1 && calls[0].who === "host", "the bare prefix /calendar/e/ is not a member route", calls);
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/calendar/events.ics?s=1", { method: "GET" }), env, { props: { caller: "qnfo-ops", member: "other" } });
  ok(calls.length === 1 && calls[0].who === "member" && calls[0].path === "/events.ics" && calls[0].search === "?s=1" && calls[0].method === "GET" && (calls[0].body === null || calls[0].body === "a=keep") && !(calls[0].props && calls[0].props.caller), "GET /calendar/events.ics reaches the member with its query, body and no binding props", calls);
  calls.length = 0;
  await W.fetch(new Request("https://qnfo-lifecycle.example/calendar/events.ics", { method: "DELETE", body: "x" }), env, {});
  ok(calls.length === 1 && calls[0].who === "host", "DELETE /calendar/events.ics is not a member route", calls);
  calls.length = 0;
  await W.fetch(new Request("https://internal/x"), env, { props: { caller: "qnfo-ops", member: "calendar-api" } });
  ok(calls[0] && /^[0-9a-f]{64}$/.test(calls[0].env.CAL_KEY_SEED || "") && calls[0].env.CAL_KEY_SEED !== env.CF_API_TOKEN && !Object.values(calls[0].env).includes(env.CF_API_TOKEN), "CAL_KEY_SEED is derived from CF_API_TOKEN and the member never sees CF_API_TOKEN", calls[0] && calls[0].env.CAL_KEY_SEED);
  { const k = await crypto.subtle.importKey("raw", new TextEncoder().encode(env.CF_API_TOKEN), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const x = Buffer.from(await crypto.subtle.sign("HMAC", k, new TextEncoder().encode("fold-kit|calendar-api|CAL_KEY_SEED"))).toString("hex"); ok(calls[0] && calls[0].env.CAL_KEY_SEED === x, "CAL_KEY_SEED is HMAC-SHA256(CF_API_TOKEN, fold-kit|calendar-api|CAL_KEY_SEED), stable across isolates"); }
  ok(calls[0] && calls[0].env.CAL_PUBLIC_BASE === "https://qnfo-lifecycle.q08.workers.dev/calendar", "the member env carries CAL_PUBLIC_BASE");
}
{
  let memberDone = false, hostRan = false; const seen = [];
  M.scheduled = async (ev, e, c) => { seen.push(ev); c.waitUntil(new Promise((r) => setTimeout(() => { memberDone = true; r(); }, 30))); };
  H.scheduled = async () => { hostRan = true; };
  const at = Date.UTC(2026, 9, 6, 11, 0, 3);
  await W.scheduled({ cron: "0 * * * *", scheduledTime: at }, env, { waitUntil(p) { Promise.resolve(p).catch(() => {}); } });
  ok(seen.length === 1 && seen[0].cron === "17 * * * *" && seen[0].tickEntry === true, "the host tick at its due time runs the member's job as a table entry", seen);
  ok(memberDone && hostRan, "the handler awaits the member's waitUntil work and runs the host's own scheduled work");
}
M.fetch = real.mf; M.scheduled = real.ms; H.fetch = real.hf; H.scheduled = real.hs;
console.log(pass + " passed, " + fail + " failed");
process.exit(fail ? 1 : 0);
