// ASK-GAP-1: questions the corpus could not answer (ask_events.uncovered) become idea proposals, once each, only when they
// pass the public research-domain gate, at most ASK_GAP_BATCH a run, and never while triage is backed up.
// Runs the worker's own runAskGap, clean and publicTitle against an in-memory SQLite D1.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { DatabaseSync } from "node:sqlite";
const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, "worker.js"), "utf8").replace(/export default\s*\{/, "var __default = {");
const sb = { console, Date, JSON, Math, Number, String, RegExp, Set, Map, Array, Object, Promise, URL, Response: class {}, Request: class {}, fetch: async () => { throw new Error("no network"); } };
vm.createContext(sb);
vm.runInContext(src + "\n__x = { runAskGap, publicTitle, ASK_GAP_BATCH, PROPOSAL_BACKPRESSURE };", sb);
const { runAskGap, publicTitle, ASK_GAP_BATCH, PROPOSAL_BACKPRESSURE } = sb.__x;
const db = new DatabaseSync(":memory:");
db.exec(`CREATE TABLE ask_events (id TEXT PRIMARY KEY, ts TEXT, qhash TEXT, query TEXT, cached INTEGER DEFAULT 0, uncovered INTEGER, error TEXT);
CREATE TABLE idea_proposals (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, idea TEXT NOT NULL, contact TEXT, status TEXT DEFAULT 'new', ip_hash TEXT, created_at TEXT, decision TEXT, score REAL, rationale TEXT, triaged_at TEXT);`);
const d1 = { prepare(sql) { let a = []; const q = sql.replace(/\?(\d+)/g, "?"); const st = { bind(...x) { a = x; return st; }, async all() { return { results: db.prepare(q).all(...a) }; }, async first() { return db.prepare(q).get(...a) ?? null; }, async run() { db.prepare(q).run(...a); return {}; } }; return st; } };
const env = { QNFO_AUDIT: d1 };
let pass = 0, fail = 0;
const ok = (c, m, d) => { if (c) pass++; else { fail++; console.log("FAIL " + m + (d === undefined ? "" : " :: " + JSON.stringify(d))); } };
let n = 0;
const ask = (q, opts = {}) => db.prepare("INSERT INTO ask_events (id, ts, qhash, query, cached, uncovered, error) VALUES (?, datetime('now', ?), ?, ?, ?, ?, ?)").run("e" + n++, opts.age || "-1 hours", opts.hash || "h-" + q.slice(0, 20), q, opts.cached || 0, opts.uncovered === undefined ? 1 : opts.uncovered, opts.error || null);
const research = "What is the energy cost per correct answer for quantum error correction on surface codes?";
ok(publicTitle(research), "fixture: the research question passes the public gate");
ask(research);
ask(research, { hash: "h-" + research.slice(0, 20) });
ask("[paper:distinction-lattice-framework] How does the distinction lattice relate to p-adic valuation in number theory?");
ask("What's the weather in Amsterdam tomorrow?");
ask("Does the Landauer bound limit surface code decoders?", { uncovered: 0 });
ask("How does ultrametric error correction compare with stabilizer codes in qubit overhead?", { cached: 1 });
ask("Is the JPCUB metric defined for analog quantum annealers and their thermodynamic cost?", { error: "timeout" });
ask("What does the adelic physics program predict for the fine-structure constant?", { age: "-10 days" });
let r = await runAskGap(env);
const rows = () => db.prepare("SELECT name, idea, ip_hash, status FROM idea_proposals ORDER BY id").all();
ok(r.inserted === 2 && rows().length === 2, "two eligible uncovered research questions become proposals", { r, rows: rows() });
ok(rows().every((x) => x.name === "ask-gap" && x.status === "new" && /^ask-gap:/.test(x.ip_hash)), "proposals are named ask-gap, status new, tagged by question hash");
ok(rows().some((x) => x.idea.startsWith("How does the distinction lattice")), "the [paper:slug] prefix of a paper-pinned ask is dropped");
ok(!rows().some((x) => /weather/.test(x.idea)), "an off-domain question is skipped by the public research gate");
ok(!rows().some((x) => /Landauer|ultrametric error|analog quantum|fine-structure/.test(x.idea)), "covered, cached, failed and older-than-7-days asks are ignored");
r = await runAskGap(env);
ok(r.inserted === 0 && rows().length === 2, "a second run inserts nothing (deduplicated)");
for (let i = 0; i < 9; i++) ask("What is the measured energy per solution for quantum annealing benchmark variant " + i + " on number partitioning?", { hash: "batch" + i });
r = await runAskGap(env);
ok(r.inserted === ASK_GAP_BATCH && ASK_GAP_BATCH <= 5, "at most ASK_GAP_BATCH proposals per run", r);
for (let i = 0; i < PROPOSAL_BACKPRESSURE + 1; i++) db.prepare("INSERT INTO idea_proposals (name, idea, status) VALUES ('x', ?, 'new')").run("p" + i);
const before = rows().length;
r = await runAskGap(env);
ok(r.paused === true && rows().length === before, "paused while more than PROPOSAL_BACKPRESSURE proposals await triage", r);
const ih = readFileSync(join(here, "worker.js"), "utf8");
ok(/r\.askgap = await runAskGap\(env\)/.test(ih), "the hourly ideation cycle runs it");
console.log(pass + " passed, " + fail + " failed");
process.exit(fail ? 1 : 0);
