const V='1.0.0',TO='rwnquni@outlook.com',OFF=[60,1440];
const iso=()=>new Date().toISOString();
const J=(d,s)=>new Response(JSON.stringify(d),{status:s||200,headers:{'content-type':'application/json','access-control-allow-origin':'*'}});
const au=(r,e)=>{const t=String(r.headers.get('Authorization')||'').replace(/^Bearer /i,'');return!e.INGEST_TOKEN||t===e.INGEST_TOKEN;};
const SCH=["CREATE TABLE IF NOT EXISTS event_inbox (id INTEGER PRIMARY KEY AUTOINCREMENT, message_id TEXT UNIQUE, from_addr TEXT, subject TEXT, raw TEXT, parsed_json TEXT, status TEXT DEFAULT 'new', calendar_event_id INTEGER, created_at TEXT DEFAULT (datetime('now')))","CREATE TABLE IF NOT EXISTS event_reminders (id INTEGER PRIMARY KEY AUTOINCREMENT, calendar_event_id INTEGER, event_title TEXT, dtstart TEXT, remind_at TEXT, sent INTEGER DEFAULT 0, sent_at TEXT)","CREATE TABLE IF NOT EXISTS event_feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, category TEXT, title TEXT, outcome TEXT, source TEXT, created_at TEXT DEFAULT (datetime('now')))","CREATE TABLE IF NOT EXISTS event_prefs (category TEXT PRIMARY KEY, accept_count INTEGER DEFAULT 0, decline_count INTEGER DEFAULT 0, last_seen TEXT)"];
const sch=async e=>{for(const s of SCH)await e.D1.prepare(s).run();};
const uf=s=>String(s).replace(/\r?\n[ \t]/g,'');
const dec=s=>{try{return atob(String(s).replace(/\s/g,''));}catch(e){return'';}};
function cps(raw){const o=[],r=String(raw||''),m=r.match(/boundary="?([^"\s\r\n]+)"?/i),b=m?m[1]:null,ss=b?r.split('--'+b):[r];for(const s of ss)if(/BEGIN:VCALENDAR/i.test(s))o.push(s);return o;}
function pb(sec){let b=sec;const h=sec.search(/\r?\n\r?\n/);if(h>=0)b=sec.slice(h).replace(/^\s+/,'');b=b.replace(/--[\s\S]*$/,'').trim();const hd=sec.split(/\r?\n\r?\n/)[0]||'';return /base64/i.test(hd)?dec(b):b.replace(/=\r?\n/g,'');}
function pv(ics){const P={};let no=false;for(const ln of uf(ics).split(/\r?\n/)){if(/^BEGIN:VALARM/i.test(ln)){no=true;continue;}if(/^END:VALARM/i.test(ln)){no=false;continue;}if(no)continue;const m=ln.match(/^([A-Za-z-]+)(;[^:]*)?:(.*)$/);if(!m)continue;const n=m[1].toUpperCase(),pm={};(m[2]||'').split(';').filter(Boolean).forEach(x=>{const q=x.match(/^([A-Za-z-]+)=(.*)$/);if(q)pm[q[1].toUpperCase()]=q[2];});if(!P[n])P[n]={v:m[3],pm:pm};}const g=n=>P[n]?P[n].v:null,gp=n=>P[n]?P[n].pm:{};return{title:g('SUMMARY')||'(untitled)',dtstart:g('DTSTART'),dsp:gp('DTSTART'),dtend:g('DTEND'),loc:g('LOCATION'),desc:g('DESCRIPTION'),uid:g('UID'),ad:((gp('DTSTART').VALUE||'').toUpperCase()==='DATE')};}
function tz(tzid,ms){try{const f=new Intl.DateTimeFormat('en-US',{timeZone:tzid,hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}),p={};for(const x of f.formatToParts(new Date(ms)))if(x.type!=='literal')p[x.type]=x.value;return Math.round((Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)-ms)/60000);}catch(e){return 0;}}
function utc(ds,pm,ad){if(!ds)return null;if(ad){const m=ds.match(/^(\d{4})(\d{2})(\d{2})/);return m?m[1]+'-'+m[2]+'-'+m[3]:ds;}const m=ds.match(/^(\d{4})(\d{2})(\d{2})T?(\d{2})(\d{2})(\d{2})?(Z)?$/);if(!m)return ds;const y=+m[1],mo=+m[2],d=+m[3],h=+m[4],mi=+m[5],s=+(m[6]||'0');if(m[7]==='Z')return new Date(Date.UTC(y,mo-1,d,h,mi,s)).toISOString();const g=Date.UTC(y,mo-1,d,h,mi,s);return new Date(g-tz((pm&&pm.TZID)||'UTC',g)*60000).toISOString();}
async function ai(e,su,bo){try{const r=await e.AI.run('@cf/meta/llama-3.3-70b-instruct-fp8-fast',{messages:[{role:'system',content:'Extract one calendar event. Reply STRICT JSON only: {"is_event":bool,"title":str,"dtstart":"ISO8601 UTC or YYYY-MM-DD","dtend":str|null,"all_day":bool,"location":str|null,"category":"meeting|flight|hotel|restaurant|delivery|health|appointment|other"}. Assume Europe/Berlin. If not an appointment/invitation/confirmation reply {"is_event":false}.'},{role:'user',content:'Subject: '+su+'\n\n'+String(bo||'').slice(0,2500)}],max_tokens:350}),t=(r&&(r.response||(r.choices&&r.choices[0]&&r.choices[0].message&&r.choices[0].message.content)))||'',m=t.match(/\{[\s\S]*\}/);return m?JSON.parse(m[0]):null;}catch(e){return null;}}
async function post(e,ev){const h={'content-type':'application/json'};if(e.CAL_EMAIL_TOKEN)h.Authorization='Bearer '+e.CAL_EMAIL_TOKEN;const r=await e.CAL_API.fetch('https://calendar-api/events?plane=personal',{method:'POST',headers:h,body:JSON.stringify(ev)});return await r.json().catch(()=>({}));}

async function ing(e,p){const mid=p.messageId||('m-'+Date.now());if(await e.D1.prepare('SELECT id FROM event_inbox WHERE message_id=?').bind(mid).first())return{duplicate:true};const ps=cps(p.raw||'');let ev=null,me='none';if(ps.length){const ics=ps.map(pb).join('\n');if(/METHOD:\s*CANCEL/i.test(ics)){me='cancel';const v=pv(ics);if(v.uid)await e.D1.prepare("UPDATE calendar SET status='cancelled', updated=datetime('now') WHERE url=?").bind('ics:'+v.uid).run();}else{const v=pv(ics);ev={title:v.title,dtstart:utc(v.dtstart,v.dsp,v.ad),dtend:utc(v.dtend,v.dsp,v.ad)||null,all_day:v.ad,location:v.loc,description:v.desc,url:v.uid?('ics:'+v.uid):null,source:'email',status:'confirmed'};me='ics';}}else{const a=await ai(e,p.subject,p.body);if(a&&a.is_event){ev={title:a.title,dtstart:a.dtstart,dtend:a.dtend||null,all_day:!!a.all_day,location:a.location||null,source:'email',status:'confirmed'};me='ai';}}if(!ev){await e.D1.prepare("INSERT INTO event_inbox (message_id,from_addr,subject,raw,parsed_json,status) VALUES (?,?,?,?,?,'ignored')").bind(mid,p.from||'',p.subject||'',String(p.raw||'').slice(0,20000),'{}').run();return{is_event:false};}const res=await post(e,ev),cid=(res&&res.id)||null;let rc=0;if(ev.dtstart){const t=Date.parse(ev.dtstart);if(isFinite(t)){const st=[];for(const o of OFF){const ra=t-o*60000;if(ra>Date.now()){st.push(e.D1.prepare('INSERT INTO event_reminders (calendar_event_id,event_title,dtstart,remind_at) VALUES (?,?,?,?)').bind(cid,ev.title,ev.dtstart,new Date(ra).toISOString()));rc++;}}if(st.length)await e.D1.batch(st);}}await e.D1.prepare("INSERT INTO event_inbox (message_id,from_addr,subject,raw,parsed_json,status,calendar_event_id) VALUES (?,?,?,?,?,'processed',?)").bind(mid,p.from||'',p.subject||'',String(p.raw||'').slice(0,20000),JSON.stringify(ev),cid).run();await e.D1.prepare("INSERT INTO event_prefs (category,accept_count,last_seen) VALUES (?,1,?) ON CONFLICT(category) DO UPDATE SET accept_count=accept_count+1,last_seen=excluded.last_seen").bind(String(ev.title||'other').slice(0,40),iso()).run().catch(()=>{});return{is_event:true,method:me,calendar_event_id:cid,reminders:rc,title:ev.title,dtstart:ev.dtstart};}
async function dis(e){const now=iso(),d=await e.D1.prepare('SELECT * FROM event_reminders WHERE sent=0 AND remind_at<=? ORDER BY remind_at LIMIT 20').bind(now).all(),s=[];for(const r of(d.results||[])){try{if(e.SEND_EMAIL)await e.SEND_EMAIL.send({to:TO,from:'qnfo@qnfo.org',subject:'Reminder: '+r.event_title,text:'Reminder: '+r.event_title+'\nWhen: '+r.dtstart});await e.D1.prepare('UPDATE event_reminders SET sent=1,sent_at=? WHERE id=?').bind(now,r.id).run();s.push(r.event_title);}catch(x){}}return s;}
export default{
async fetch(req,e){const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*'}});if(p==='/health')return J({ok:true,worker:'qnfo-calendar-intake',version:V,ts:iso()});if(!au(req,e))return J({error:'unauthorized'},401);
if(p==='/ingest'&&req.method==='POST'){const b=await req.json().catch(()=>null);if(!b)return J({error:'json required'},400);await sch(e);return J(await ing(e,b));}
if(p==='/feedback'&&req.method==='POST'){const b=await req.json().catch(()=>({}));await sch(e);if(b.calendar_event_id)await e.D1.prepare("UPDATE calendar SET status='cancelled', updated=datetime('now') WHERE id=?").bind(b.calendar_event_id).run();await e.D1.prepare('INSERT INTO event_feedback (category,title,outcome,source) VALUES (?,?,?,?)').bind(String(b.category||'other').slice(0,40),b.title||'',b.outcome||'declined','manual').run();const c=(b.outcome==='declined'||b.outcome==='cancelled')?'decline_count':'accept_count';await e.D1.prepare('INSERT INTO event_prefs (category,'+c+',last_seen) VALUES (?,1,?) ON CONFLICT(category) DO UPDATE SET '+c+'='+c+'+1,last_seen=excluded.last_seen').bind(String(b.category||'other').slice(0,40),iso()).run();return J({ok:true});}
if(p==='/run-reminders')return J({ok:true,sent:await dis(e)});
if(p==='/prefs'){const r=await e.D1.prepare('SELECT * FROM event_prefs ORDER BY (accept_count+decline_count) DESC LIMIT 50').all();return J({prefs:r.results||[]});}
if(p==='/inbox'){const r=await e.D1.prepare('SELECT id,message_id,subject,status,calendar_event_id,created_at FROM event_inbox ORDER BY id DESC LIMIT 50').all();return J({inbox:r.results||[]});}
if(p==='/reminders'){const r=await e.D1.prepare('SELECT * FROM event_reminders ORDER BY remind_at DESC LIMIT 50').all();return J({reminders:r.results||[]});}
return J({ok:true,worker:'qnfo-calendar-intake',version:V});},
async scheduled(ev,e,ctx){ctx.waitUntil((async()=>{await sch(e);await dis(e);})().catch(()=>{}));}
};
