// MD-INLINE-1 (qnfo-gateway 3.14.0): titles and abstracts read as inline Markdown with math; plain variants for metadata.
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const here = dirname(fileURLToPath(import.meta.url));
const dir = mkdtempSync(join(tmpdir(), "gwm-"));
writeFileSync(join(dir, "w.mjs"), readFileSync(join(here, "worker.js"), "utf8") + "\nexport { titleHTML, displayTitle, mathPlain, mdPlain, absHTML, lpExcerpt, lpDoi, buildPaperJsonLd };\n");
const { titleHTML, displayTitle, mathPlain, mdPlain, absHTML, lpExcerpt, lpDoi, buildPaperJsonLd } = await import(pathToFileURL(join(dir, "w.mjs")).href);
let fails = 0;
const ok = (c, m, x) => { console.log((c ? "PASS " : "FAIL ") + m); if (!c) { fails++; if (x !== undefined) console.log("   ", JSON.stringify(x).slice(0, 400)); } };
let h = titleHTML("The *thermodynamic wall* and **strong** claims");
ok(h === "The <em>thermodynamic wall</em> and <strong>strong</strong> claims", "title italics and bold", h);
h = titleHTML("Why _p_-adic trees matter");
ok(/<em>p<\/em>-adic/.test(h), "underscore emphasis at a word boundary", h);
h = titleHTML("Degrees in Isabelle/ML: the poly_degree Command and snake_case_names");
ok(!/<em>/.test(h) && /poly_degree/.test(h) && /snake_case_names/.test(h), "snake_case is never emphasis", h);
h = titleHTML("The $\\mathcal{T}_p$ tree and *its* $p$-adic spectrum");
ok(h.includes("$\\mathcal{T}_p$") && h.includes("<em>its</em>") && h.includes("$p$-adic") && !/<em>p/.test(h), "math is kept as delimiters for MathJax and its underscores are not emphasis", h);
h = titleHTML("*A $p$-adic tree*");
ok(h === "<em>A $p$-adic tree</em>", "emphasis may wrap a math span", h);
h = titleHTML("The $1,032 Research Program and $5 per run");
ok(!/\$1,032 Research Program and \$/.test(h.replace(/<span class="usd">\$<\/span>/g, "¤")) && (h.match(/class="usd"/g) || []).length === 2, "currency dollars stay literal and cannot pair as math", h);
ok(displayTitle("The *thermodynamic wall* of $\\mathbb{Z}_p$") === "The thermodynamic wall of ℤ_p" || /thermodynamic wall of /.test(displayTitle("The *thermodynamic wall* of $\\mathbb{Z}_p$")) && !/\*/.test(displayTitle("The *thermodynamic wall* of $\\mathbb{Z}_p$")), "displayTitle (the <title>/og/RSS text) has no emphasis marks", displayTitle("The *thermodynamic wall* of $\\mathbb{Z}_p$"));
ok(displayTitle("The $1,032 Research Program") === "The $1,032 Research Program", "displayTitle keeps a currency dollar", displayTitle("The $1,032 Research Program"));
const ab = "We introduce the *thermodynamic wall*: a bound on $E \\geq k_B T \\ln 2$ for **every** system. Costs $5 and $6 stay literal.";
h = absHTML(ab, 300);
ok(h.includes("<em>thermodynamic wall</em>") && h.includes("<strong>every</strong>") && h.includes("$E \\geq k_B T \\ln 2$"), "abstract preview renders emphasis and keeps math for MathJax", h);
const p = mdPlain(ab);
ok(!/[*]/.test(p) && !/\\geq/.test(p) && /thermodynamic wall/.test(p) && /\$5 and \$6/.test(p), "plain abstract has no markup or TeX and keeps currency", p);
const long = "Intro *word* ".repeat(5) + "then math $\\sum_{i=1}^{n} x_i^2 + \\int_0^1 f(x)\\,dx$ ending " + "tail words ".repeat(20);
h = absHTML(long, 90);
ok(((h.match(/\$/g) || []).length % 2) === 0 && /…$/.test(h), "a truncated preview never cuts inside a math span", h);
ok(!/[*$\\]/.test(lpExcerpt(long, 90).replace(/…/, "")), "plain excerpt is readable text", lpExcerpt(long, 90));
ok(mathPlain("a *b* and $x^2$") === "a b and x²", "mathPlain strips emphasis and converts math", mathPlain("a *b* and $x^2$"));
const ld = buildPaperJsonLd({ slug: "s", title: "The *wall* of $p$", abstract: "An *italic* claim about $\\alpha$.", doi: "10." + "5281/zen" + "odo.1", authors: "[]", created_at: "2026-10-01" });
ok(!/[*]|\\\\alpha|10\.5281|zeno\x64o|PropertyValue/.test(ld) && /"headline":"The wall of p"/.test(ld), "JSON-LD has plain title and abstract and no deposit DOI", ld);
ok(lpDoi("10.1234/abc") === "10.1234/abc" && lpDoi("10." + "5281/x") === null, "third-party DOIs pass, the retired prefix does not");
console.log(fails ? fails + " failure(s)" : "all passed");
process.exit(fails ? 1 : 0);
