// MATH-DELIM-1 / TABLE-SEP-1 (qnfo-gateway 3.8.2): renderer regressions found by the full-corpus sweep of 2026-10-02.
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const here = dirname(fileURLToPath(import.meta.url));
const dir = mkdtempSync(join(tmpdir(), "gwr-"));
writeFileSync(join(dir, "w.mjs"), readFileSync(join(here, "worker.js"), "utf8") + "\nexport { renderMarkdown, lpStructure, lpDoi };\n");
const { renderMarkdown, lpStructure, lpDoi } = await import(pathToFileURL(join(dir, "w.mjs")).href);
let fails = 0;
const ok = (c, m, x) => { console.log((c ? "PASS " : "FAIL ") + m); if (!c) { fails++; if (x) console.log("   ", JSON.stringify(x).slice(0, 400)); } };
const math = (h) => (h.replace(/<span class="usd">\$<\/span>/g, "\u00a4").replace(/<[^>]+>/g, " ").match(/\$[^$]+\$/g) || []);
let h = renderMarkdown("The claim: **anyons are not particles in $\\mathbb{R}$$^3$ but patterns.**\n\n| A | B |\n|---|---|\n| 1 | 2 |\n\n## Next");
ok(/<table>/.test(h) && /<h2>Next<\/h2>/.test(h) && math(h).includes("$\\mathbb{R}^3$"), "adjacent inline formulas no longer open display math (the table and heading after them render)", h);
h = renderMarkdown("Spend: **$1,032.08 total** across 184 days, a mean of $5.61 per day.");
ok(math(h).length === 0 && /<strong>/.test(h) && (h.match(/<span class="usd">\$<\/span>/g) || []).length === 2, "currency is not math, and literal dollars cannot be paired by MathJax", h);
h = renderMarkdown("Bound: $\\leq$0.75 and $x$ and $ f: \\mathbb{Z}_p \\to \\mathbb{Q}_p $ and $2^n$ states.");
ok(math(h).length === 4, "real formulas survive: followed by a digit, spaces inside, starting with a digit", math(h));
h = renderMarkdown("The ratios $m_\\mu/m_e \\approx\n207$ and $m_\\tau/m_e$ are close.");
ok(math(h).length === 2, "a formula broken across a line still renders", math(h));
h = renderMarkdown("| # | Objection | Grade |\n|:--|:----------|:------|\n| 1 | Chronological | Partial |");
ok(/<table>/.test(h) && /<th>#<\/th>/.test(h) && !/<h1>/.test(h), "short GFM delimiter rows (|:--|) make a table; a '#' header cell is not a heading", h);
h = renderMarkdown("Price \\$5 and more.");
ok(!math(h).length && /usd/.test(h), "an escaped dollar stays literal", h);
const st = lpStructure("<h1>1. What this is</h1><p>x</p><h2>1.1 Part</h2><p>y</p><h1>2. Next</h1>");
ok(!/<h1/.test(st.html) && st.toc.length === 3 && st.toc[0].lv === 2 && st.toc[1].lv === 3, "papers that use # for sections get h2 sections in the contents", st.toc);
ok(lpDoi("pending") === null && lpDoi("https://doi.org/10.5281/zenodo.21758752") === "10.5281/zenodo.21758752" && lpDoi("10.5281/zenodo.1") === "10.5281/zenodo.1" && lpDoi("") === null, "DOI-HYGIENE-1: only real DOIs are shown (\"pending\" and URL forms handled)");
h = renderMarkdown("Code:\n[](#cb1-1)import numpy as np\n[](#cb1-2)var = np.sum(prob * dist**2)\n[](#cb1-3)return var\n\nAfter.");
ok(/<pre><code>/.test(h) && /dist\*\*2/.test(h) && !/#cb1/.test(h) && !/<strong>/.test(h), "PANDOC-CODE-1: anchored code lines become one code block; ** stays an operator", h);
h = renderMarkdown("# **Appendix A: Formal Proof of Emergent Temporal\ndynamics**\n\nText.");
ok(/<h1><strong>Appendix A: Formal Proof of Emergent Temporal dynamics<\/strong><\/h1>/.test(h), "HEADING-WRAP-1: a heading wrapped onto the next line is joined", h);
// RENDER-FIX-3 (3.9.1)
h = renderMarkdown("Sample $s \\xleftarrow{\\$} \\mathbb{Z}_p^n$ uniformly, a sub-\\$500K program, and $x$.");
ok(math(h).length === 2 && math(h)[0].indexOf("xleftarrow") > 0 && (h.match(/usd/g) || []).length === 1, "RENDER-FIX-3: an escaped dollar inside a formula or before a number is never a delimiter", math(h));
h = renderMarkdown("Code:\n\n```python\nx = 1  # a comment\n```\n\nAfter.");
ok(!/<h1>/.test(h) && /x = 1  # a comment/.test(h), "RENDER-FIX-3: a comment in fenced code stays on its line (no heading)", h);
h = renderMarkdown("Code:\n[](#cb1-1)rho = c**5\n[](#cb1-2)        # Store state\n[](#cb1-3)return rho\n\nAfter.");
ok(!/<h1>/.test(h) && (h.match(/<pre>/g) || []).length === 1 && /# Store state/.test(h), "RENDER-FIX-3: a comment in pandoc-anchored code stays in the one code block", h);
h = renderMarkdown("| Lepton | Crossing # $n$ |\n|:--|:--|\n| e | 0 |");
ok(/<table>/.test(h) && !/<h1>/.test(h) && /<td>e<\/td>/.test(h), "RENDER-FIX-3: a '#' inside a table header cell does not split the row into a heading", h);
h = renderMarkdown("the model operates. ######\n**1.3.1.1. Ptolemy's Model's Paradoxical\nSuccess** A detailed recounting.\n\n#\n## Changelog\n\n- v2");
ok(/<h6>1\.3\.1\.1\. Ptolemy.s Model.s Paradoxical Success<\/h6>/.test(h) && /<p>A detailed recounting\.<\/p>/.test(h) && /<h2>Changelog<\/h2>/.test(h) && !/<p>#/.test(h) && !/\*\*/.test(h), "RENDER-FIX-3: a heading marker at the end of a line takes the bold line after it; a bare marker is dropped", h);
h = renderMarkdown("- **Experimental tests of consciousness\nmeasurement.** While controversial.\n- Next");
ok((h.match(/<li>/g) || []).length === 2 && /<strong>Experimental tests of consciousness measurement\.<\/strong>/.test(h), "RENDER-FIX-3: list items take lazy continuation lines", h);
h = renderMarkdown("**5.5.2.2 A New Lens: an *additional, orthogonal lens* for biology.** Text ***both***.");
ok(/<strong>5\.5\.2\.2 A New Lens: an <em>additional, orthogonal lens<\/em> for biology\.<\/strong>/.test(h) && /<strong><em>both<\/em><\/strong>/.test(h) && !/\*/.test(h), "RENDER-FIX-3: bold containing italic, and bold italic", h);
h = renderMarkdown("Let \\(D_0\n= \\{\\bot\\}\\) be flat.");
ok(math(h).length === 1 && math(h)[0] === "$D_0 = \\{\\bot\\}$", "RENDER-FIX-3: \\( ... \\) may wrap onto the next line", math(h));
h = renderMarkdown("**Table 2: Cost**\n\nScenario |\nFab Yield |\nCost (\\$M) |\n|\n\nStandard |\n95% |\n\\$10.53 |\n\n**Topological\n(Baseline)** |\n**50%** |\n**\\$1.00** |\n\nAfter the table.");
ok(/<table><thead><tr><th>Scenario<\/th><th>Fab Yield<\/th><th>Cost/.test(h) && (h.match(/<tr>/g) || []).length === 3 && /<strong>Topological \(Baseline\)<\/strong>/.test(h) && /<p>After the table\.<\/p>/.test(h) && !/\|/.test(h), "FLAT-TABLE-1: docx tables flattened into 'cell |' paragraphs become tables", h);
h = renderMarkdown("The construction proceeds through inverse limits: |\n\nNext paragraph.");
ok(!/<table>/.test(h) && /inverse limits:<\/p>/.test(h), "FLAT-TABLE-1: a one-cell row is prose without its stray pipe", h);
console.log(fails + " failure(s)");
process.exit(fails ? 1 : 0);
